In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.patches as mpatch
import matplotlib.cm as cmpl
import matplotlib.colors as mpcolors
import seaborn as sns
import squarify as sq
%matplotlib inline

C:\Users\chris\AppData\Local\Temp\ipykernel_18812\1554565068.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

## Uploading my Data

In [2]:
def upload(fileName):
    df = pd.read_csv(fileName)
    return df

In [3]:
firearm_intersection = upload('./Datasets/firearm_data_intersections13to17.csv')

In [4]:
firearm_address = upload('./Datasets/FirearmAddress.csv')

In [5]:
firearm_general = upload('./Datasets/FirearmsData.csv')

In [6]:
jan_firearm_auction = upload('./Datasets/Jan2021FirearmsAuction.csv')

## Exploring my Data

Before I can merge these datasets, I want to make sure the column names and values are the same.

### Intersection Dataset

In [7]:
firearm_intersection.head()

,incident_number,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,recovery_date,address_geocode_type,recovery_block_address,city,...,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,address_concat,x,y,longitude,latitude,confidence,source
0,80-13-097166,Narcotics,"Pistol, Semi-automatic ...",Ruger,Sr9c,9MM,2013-12-20 00:00:00+00,INTERSECTION,N 22nd St / Bank St,Louisville,...,Black,M,21.0,N 22nd St / Bank St Louisville KY 40203,NaN,NaN,NaN,NaN,NaN,NaN
1,80-11-044948,Wpns Law Violation,"Pistol, Semi-automatic ...",Intratec,NaN,9MM,2011-06-11 00:00:00+00,INTERSECTION,7th Street Rd / Berry Blvd,Louisville,...,Black,M,20.0,7th Street Rd / Berry Blvd Louisville KY 40216,NaN,NaN,NaN,NaN,NaN,NaN
2,80-11-037378,Narcotics,"Rifle, Semi-automatic ...",Norinco,Sks,762M,2011-05-16 00:00:00+00,INTERSECTION,N 37th St / Bank St,Louisville,...,White,M,27.0,N 37th St / Bank St Louisville KY 40212,NaN,NaN,NaN,NaN,NaN,NaN
3,80-12-061676,Wpns Law Violation,"Pistol, Revolver ...",NaN,NaN,38C,2012-08-03 00:00:00+00,INTERSECTION,Dixie Hwy / Ralph Ave,Shively,...,Black,M,53.0,Dixie Hwy / Ralph Ave Shively KY,1195202.125,260851.7188,-85.799466,38.206025,NaN,LOJIC
4,80-12-010689,Narcotics,Null,NaN,Airmaster,NaN,2012-02-16 00:00:00+00,INTERSECTION,Oxmoor Ln / Shelbyville Rd,Norwood,...,White,M,36.0,Oxmoor Ln / Shelbyville Rd Norwood KY 40222,1248916.500,275799.8750,-85.613325,38.249400,NaN,LOJIC

In [8]:
firearm_intersection.columns

Index(['incident_number', 'ucr_category', 'type_of_firearm',
       'firearm_manufacturer', 'firearm_model', 'firearm_caliber',
       'recovery_date', 'address_geocode_type', 'recovery_block_address',
       'city', 'state', 'recovery_zipcode', 'person_recovered_from_race',
       'person_recovered_from_sex', 'person_recovered_from_age',
       'address_concat', 'x', 'y', 'longitude', 'latitude', 'confidence',
       'source'],
      dtype='object')

In [9]:
firearm_intersection.dtypes

incident_number                object
ucr_category                   object
type_of_firearm                object
firearm_manufacturer           object
firearm_model                  object
firearm_caliber                object
recovery_date                  object
address_geocode_type           object
recovery_block_address         object
city                           object
state                          object
recovery_zipcode              float64
person_recovered_from_race     object
person_recovered_from_sex      object
person_recovered_from_age     float64
address_concat                 object
x                             float64
y                             float64
longitude                     float64
latitude                      float64
confidence                    float64
source                         object
dtype: object

### Address Dataset

In [10]:
firearm_address.head()

,INCIDENT_NUMBER,UCR_CATEGORY,TYPE_OF_FIREARM,FIREARM_MANUFACTURER,FIREARM_MODEL,FIREARM_CALIBER,RECOVERY_DATE,ADDRESS_GEOCODE_TYPE,RECOVERY__ADDRESS,CITY,state,RECOVERY_ZIPCODE,PERSON_RECOVERED_FROM_RACE,PERSON_RECOVERED_FROM_SEX,PERSON_RECOVERED_FROM_AGE,Address_Concat,Longitude,Latitude,Confidence,Source
0,80-10-011494,Wpns Law Violation,"Pistol, Semi-automatic",Manurin S.A.,NaN,765M,2010-02-17T00:00:00Z,BLOCK,9400 National Tpke,Louisville,KY,40118.0,White,M,44.0,9400 National Tpke Louisville KY 40118,-85.752898,38.125321,0.54,openaddresses
1,80-10-011506,Narcotics,"Shotgun, Pump Action",Remington Arms,Shotgun: Model,20GA,2010-02-17T00:00:00Z,BLOCK,4500 Landside Dr,Louisville,KY,40220.0,Black,M,19.0,4500 Landside Dr Louisville KY 40220,-85.620998,38.198673,1.00,openaddresses
2,80-10-011506,Narcotics,"Shotgun, Pump Action",Remington Arms,Shotgun: Model,20GA,2010-02-17T00:00:00Z,BLOCK,4500 Landside Dr,Louisville,KY,40220.0,Black,M,19.0,4500 Landside Dr Louisville KY 40220,-85.620998,38.198673,1.00,openaddresses
3,80-10-011506,Narcotics,"Shotgun, Pump Action",Remington Arms,Shotgun: Model,20GA,2010-02-17T00:00:00Z,BLOCK,4500 Landside Dr,Louisville,KY,40220.0,Black,M,19.0,4500 Landside Dr Louisville KY 40220,-85.620998,38.198673,1.00,openaddresses
4,80-10-011506,Narcotics,"Shotgun, Pump Action",Remington Arms,Shotgun: Model,20GA,2010-02-17T00:00:00Z,BLOCK,4500 Landside Dr,Louisville,KY,40220.0,Black,M,19.0,4500 Landside Dr Louisville KY 40220,-85.620998,38.198673,1.00,openaddresses

In [11]:
firearm_address.columns

Index(['INCIDENT_NUMBER', 'UCR_CATEGORY', 'TYPE_OF_FIREARM',
       'FIREARM_MANUFACTURER', 'FIREARM_MODEL', 'FIREARM_CALIBER',
       'RECOVERY_DATE', 'ADDRESS_GEOCODE_TYPE', 'RECOVERY__ADDRESS', 'CITY',
       'state', 'RECOVERY_ZIPCODE', 'PERSON_RECOVERED_FROM_RACE',
       'PERSON_RECOVERED_FROM_SEX', 'PERSON_RECOVERED_FROM_AGE',
       'Address_Concat', 'Longitude', 'Latitude', 'Confidence', 'Source'],
      dtype='object')

In [12]:
firearm_address.dtypes

INCIDENT_NUMBER                object
UCR_CATEGORY                   object
TYPE_OF_FIREARM                object
FIREARM_MANUFACTURER           object
FIREARM_MODEL                  object
FIREARM_CALIBER                object
RECOVERY_DATE                  object
ADDRESS_GEOCODE_TYPE           object
RECOVERY__ADDRESS              object
CITY                           object
state                          object
RECOVERY_ZIPCODE              float64
PERSON_RECOVERED_FROM_RACE     object
PERSON_RECOVERED_FROM_SEX      object
PERSON_RECOVERED_FROM_AGE     float64
Address_Concat                 object
Longitude                     float64
Latitude                      float64
Confidence                    float64
Source                         object
dtype: object

### General Dataset

In [13]:
firearm_general.head()

,INCIDENT_NUMBER,UCR_CATEGORY,TYPE_OF_FIREARM,FIREARM_MANUFACTURER,FIREARM_MODEL,FIREARM_CALIBER,RECOVERY_DATE,RECOVERY_BLOCK_ADDRESS,CITY,state,RECOVERY_ZIPCODE,PERSON_RECOVERED_FROM_RACE,PERSON_RECOVERED_FROM_SEX,PERSON_RECOVERED_FROM_AGE,year
0,80-06-008380,HOMICIDE,NaN,NaN,NaN,NaN,NaN,NaN,LOUISVILLE,KY,40202,NaN,NaN,NaN,NaN
1,80-10-002211,HOMICIDE,NaN,NaN,NaN,NaN,NaN,NaN,LOUISVILLE,KY,40202,NaN,NaN,NaN,NaN
2,80-10-002211,HOMICIDE,NaN,NaN,NaN,NaN,NaN,NaN,LOUISVILLE,KY,40202,NaN,NaN,NaN,NaN
3,80-17-000578,SUICIDE,NaN,NaN,NaN,NaN,NaN,NaN,LOUISVILLE,KY,40272,NaN,NaN,NaN,NaN
4,80-17-001680,SUICIDE,NaN,NaN,NaN,NaN,NaN,NaN,LOUISVILLE,KY,40272,NaN,NaN,NaN,NaN

In [14]:
firearm_general.columns

Index(['INCIDENT_NUMBER', 'UCR_CATEGORY', 'TYPE_OF_FIREARM',
       'FIREARM_MANUFACTURER', 'FIREARM_MODEL', 'FIREARM_CALIBER',
       'RECOVERY_DATE', 'RECOVERY_BLOCK_ADDRESS', 'CITY', 'state',
       'RECOVERY_ZIPCODE', 'PERSON_RECOVERED_FROM_RACE',
       'PERSON_RECOVERED_FROM_SEX', 'PERSON_RECOVERED_FROM_AGE', 'year'],
      dtype='object')

In [15]:
firearm_general.dtypes

INCIDENT_NUMBER                object
UCR_CATEGORY                   object
TYPE_OF_FIREARM                object
FIREARM_MANUFACTURER           object
FIREARM_MODEL                  object
FIREARM_CALIBER                object
RECOVERY_DATE                  object
RECOVERY_BLOCK_ADDRESS         object
CITY                           object
state                          object
RECOVERY_ZIPCODE               object
PERSON_RECOVERED_FROM_RACE     object
PERSON_RECOVERED_FROM_SEX      object
PERSON_RECOVERED_FROM_AGE     float64
year                          float64
dtype: object

## Changing the Data Format

The column names are the same except for some additions in firearm_general and firearm_intersection, so I just want to make sure that the names look exactly the same before I combine the datasets.

### Changing the upper-case column names to lower-case

In [16]:
firearm_address.columns = ['incident_number',
                          'ucr_category',
                          'type_of_firearm',
                          'firearm_manufacturer',
                          'firearm_model',
                          'firearm_caliber',
                          'recovery_date',
                          'address_geocode_type',
                          'recovery_address',
                          'city',
                          'state',
                          'recovery_zipcode',
                          'person_recovered_from_race',
                          'person_recovered_from_sex',
                          'person_recovered_from_age',
                          'address_concat',
                          'longitude',
                          'latitude',
                          'confidence',
                          'source']

In [17]:
firearm_general.columns = ['incident_number',
                          'ucr_category',
                          'type_of_firearm',
                          'firearm_manufacturer',
                          'firearm_model',
                          'firearm_caliber',
                          'recovery_date',
                          'recovery_block_address',
                          'city',
                          'state',
                          'recovery_zipcode',
                          'person_recovered_from_race',
                          'person_recovered_from_sex',
                          'person_recovered_from_age',
                          'year']

In [18]:
firearm_address.columns

Index(['incident_number', 'ucr_category', 'type_of_firearm',
       'firearm_manufacturer', 'firearm_model', 'firearm_caliber',
       'recovery_date', 'address_geocode_type', 'recovery_address', 'city',
       'state', 'recovery_zipcode', 'person_recovered_from_race',
       'person_recovered_from_sex', 'person_recovered_from_age',
       'address_concat', 'longitude', 'latitude', 'confidence', 'source'],
      dtype='object')

In [19]:
firearm_general.columns

Index(['incident_number', 'ucr_category', 'type_of_firearm',
       'firearm_manufacturer', 'firearm_model', 'firearm_caliber',
       'recovery_date', 'recovery_block_address', 'city', 'state',
       'recovery_zipcode', 'person_recovered_from_race',
       'person_recovered_from_sex', 'person_recovered_from_age', 'year'],
      dtype='object')

In [20]:
firearm_intersection.columns

Index(['incident_number', 'ucr_category', 'type_of_firearm',
       'firearm_manufacturer', 'firearm_model', 'firearm_caliber',
       'recovery_date', 'address_geocode_type', 'recovery_block_address',
       'city', 'state', 'recovery_zipcode', 'person_recovered_from_race',
       'person_recovered_from_sex', 'person_recovered_from_age',
       'address_concat', 'x', 'y', 'longitude', 'latitude', 'confidence',
       'source'],
      dtype='object')

### Dropping Duplicate Rows

Now that I have ensured all my columns look the same and contain the same names, I want to drop all of my duplicate rows before I merge them.

In [21]:
firearm_intersection = firearm_intersection.drop_duplicates()

In [22]:
firearm_address = firearm_address.drop_duplicates()

In [23]:
firearm_general = firearm_general.drop_duplicates()

### Changing data values from upper-case to lower-case

In the datasets where we had to change the column names from upper case to lower case, the data within is also in lower case. Let's see if we can go ahead and change these data values from objects to strings and from upper case to lower case at the same time. Luckily, the only dataset we should have to do this with is the firearm_general.

In [24]:
firearm_general['ucr_category'] = firearm_general['ucr_category'].str.title()
firearm_general['type_of_firearm'] = firearm_general['type_of_firearm'].str.title()
firearm_general['firearm_manufacturer'] = firearm_general['firearm_manufacturer'].str.title()
firearm_general['firearm_model'] = firearm_general['firearm_model'].str.title()
firearm_general['recovery_block_address'] = firearm_general['recovery_block_address'].str.title()
firearm_general['city'] = firearm_general['city'].str.title()
firearm_general['person_recovered_from_race'] = firearm_general['person_recovered_from_race'].str.title()

In [25]:
firearm_general

,incident_number,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,recovery_date,recovery_block_address,city,state,recovery_zipcode,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,year
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,40202,NaN,NaN,NaN,NaN
1,80-10-002211,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,40202,NaN,NaN,NaN,NaN
3,80-17-000578,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,40272,NaN,NaN,NaN,NaN
4,80-17-001680,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,40272,NaN,NaN,NaN,NaN
5,80-17-002802,Death Investigation,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,40211,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14843,80-10-000185,Narcotics,"Pistol, Semi-Automatic ...",Smith & Wesson ...,Sw40Ve,40C,1/1/2010,9200 Block Sissonne Dr ...,Louisville,KY,40118,White,M,27.0,2010.0
14845,80-09-099274,Aggravated Assault,"Pistol, Semi-Automatic ...",...,,9MM,12/31/2009,700 Block Heywood Ave ...,Louisville,KY,40208,Black,M,23.0,2009.0
14846,80-09-098505,Aggravated Assault,NaN,Armory Gun Co. ...,,,12/29/2009,400 Block Amy Ave ...,Louisville,KY,40212,Black,M,56.0,2009.0
14847,80-09-098505,Aggravated Assault,NaN,...,,,12/29/2009,400 Block Amy Ave ...,Louisville,KY,40212,Black,M,56.0,2009.0
14848,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,40203,White,M,15.0,2008.0

## Merging Datasets

### Merging the Intersection and Address sets

After several tries, I figured out the merge function doesn't enjoy having to merge with more than one identical column. I'm going to merge the intersection and address datasets first, then tack on the general after. Between the intersection and address datasets, the column I want to merge on is the incident_number, and the additional columns I want to add are the recovery_block_address, x, and y. 

So, I'm going to make a different dataframe called firearm_to_merge which contains all the columns from firearm_intersection that I want to merge with firearm_address.

In [26]:
firearm_to_merge = firearm_intersection[['incident_number', 'recovery_block_address', 'x', 'y']]

The original dataset included 2746 pieces of data (rows) and the one we want to merge has 2213 pieces of data, so we know that there were 533 duplicate rows in our data that were successfully dropped.

In [27]:
firearm_to_merge

,incident_number,recovery_block_address,x,y
0,80-13-097166,N 22nd St / Bank St,NaN,NaN
1,80-11-044948,7th Street Rd / Berry Blvd,NaN,NaN
2,80-11-037378,N 37th St / Bank St,NaN,NaN
3,80-12-061676,Dixie Hwy / Ralph Ave,1195202.125,260851.7188
4,80-12-010689,Oxmoor Ln / Shelbyville Rd,1248916.500,275799.8750
...,...,...,...,...
2741,80-13-089244,W Pages Ln / Terry Rd,NaN,NaN
2742,80-12-085476,W Southern Heights Ave / Wheeler Ave,1198203.750,254911.1250
2743,80-16-075482,W Southern Heights Ave / Woodruff Ave,1199311.250,254829.2813
2744,80-10-073277,Watterson Trl / Whitfield Dr,NaN,NaN
2745,80-16-021321,Whisp Brook Cir / Whispering Brook Dr,1223493.625,223231.6875

Now we can merge the data to get half the dataset we want.

**Actual Merge:**

In [28]:
firearm_half = pd.merge(firearm_address, firearm_to_merge, how = 'outer', on =["incident_number"])

In [29]:
firearm_half

,incident_number,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,recovery_date,address_geocode_type,recovery_address,city,...,person_recovered_from_sex,person_recovered_from_age,address_concat,longitude,latitude,confidence,source,recovery_block_address,x,y
0,80-06-008380,Homicide,Null,Null,Null,NaN,NaN,NO ADDRESS,Null,Louisville,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-shot",Marlin Firearms Co.,Modle 25 Series,NaN,2014-07-30T00:00:00Z,BLOCK,4700 Haney Way,Louisville,...,M,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN
2,80-08-008343,Burglary,"Pistol, Semi-automatic",Jennings Firear,Jennings Firear,380C,2010-01-20T00:00:00Z,BLOCK,3400 Shagbark Rd,Louisville,...,M,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN
3,80-08-047627,Aggravated Assault,"Pistol, Semi-automatic",Parabellum,NaN,9MM,2012-06-18T00:00:00Z,BLOCK,1700 W Hill St,Louisville,...,M,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-automatic",Fie,E28,25C,2008-11-29T00:00:00Z,BLOCK,1000 Cladwell,Louisville,...,M,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10470,80-17-014610,Wpns Law Violation,"Pistol, Semi-automatic",Jimenez Arms,See Bryco,380C,2017-02-20T00:00:00Z,BLOCK,2500 Alanmede Rd,Louisville,...,M,16.0,2500 Alanmede Rd Louisville KY 40205,-85.667457,38.216242,1.00,openaddresses,NaN,NaN,NaN
10471,80-17-014921,Wpns Law Violation,Null,"Glock, Inc.",Model 31/31c (3,NaN,2017-02-21T00:00:00Z,BLOCK,600 W Jefferson St,Louisville,...,M,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN
10472,80-17-014942,Narcotics,"Pistol, Semi-automatic",Cobra Enterprises Inc,Ca Series,380C,2017-02-21T00:00:00Z,BLOCK,4200 S 2nd St,Louisville,...,F,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN
10473,80-17-015000,Wpns Law Violation,"Pistol, Semi-automatic","Glock, Inc.",NaN,45C,2017-02-21T00:00:00Z,BLOCK,4500 S 6th St,Louisville,...,M,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN
10474,80-17-015302,Suicide,Null,Null,Null,NaN,NaN,NO ADDRESS,Null,Louisville,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN

Since we're merging two dataframes, I just want to double-check that there are no duplicates.

In [30]:
firearm_half = firearm_half.drop_duplicates()

In [31]:
firearm_half

,incident_number,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,recovery_date,address_geocode_type,recovery_address,city,...,person_recovered_from_sex,person_recovered_from_age,address_concat,longitude,latitude,confidence,source,recovery_block_address,x,y
0,80-06-008380,Homicide,Null,Null,Null,NaN,NaN,NO ADDRESS,Null,Louisville,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-shot",Marlin Firearms Co.,Modle 25 Series,NaN,2014-07-30T00:00:00Z,BLOCK,4700 Haney Way,Louisville,...,M,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN
2,80-08-008343,Burglary,"Pistol, Semi-automatic",Jennings Firear,Jennings Firear,380C,2010-01-20T00:00:00Z,BLOCK,3400 Shagbark Rd,Louisville,...,M,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN
3,80-08-047627,Aggravated Assault,"Pistol, Semi-automatic",Parabellum,NaN,9MM,2012-06-18T00:00:00Z,BLOCK,1700 W Hill St,Louisville,...,M,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-automatic",Fie,E28,25C,2008-11-29T00:00:00Z,BLOCK,1000 Cladwell,Louisville,...,M,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10470,80-17-014610,Wpns Law Violation,"Pistol, Semi-automatic",Jimenez Arms,See Bryco,380C,2017-02-20T00:00:00Z,BLOCK,2500 Alanmede Rd,Louisville,...,M,16.0,2500 Alanmede Rd Louisville KY 40205,-85.667457,38.216242,1.00,openaddresses,NaN,NaN,NaN
10471,80-17-014921,Wpns Law Violation,Null,"Glock, Inc.",Model 31/31c (3,NaN,2017-02-21T00:00:00Z,BLOCK,600 W Jefferson St,Louisville,...,M,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN
10472,80-17-014942,Narcotics,"Pistol, Semi-automatic",Cobra Enterprises Inc,Ca Series,380C,2017-02-21T00:00:00Z,BLOCK,4200 S 2nd St,Louisville,...,F,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN
10473,80-17-015000,Wpns Law Violation,"Pistol, Semi-automatic","Glock, Inc.",NaN,45C,2017-02-21T00:00:00Z,BLOCK,4500 S 6th St,Louisville,...,M,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN
10474,80-17-015302,Suicide,Null,Null,Null,NaN,NaN,NO ADDRESS,Null,Louisville,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN

Since we did an outer merge so we didn't lose data, we did have some duplicate values we had to get rid of. Now, we can go ahead and merge the general dataset.

### Adding on the General set

In [32]:
firearm_data = pd.merge(firearm_general, firearm_half, how='outer', on=['incident_number'])

In [33]:
firearm_data

,incident_number,ucr_category_x,type_of_firearm_x,firearm_manufacturer_x,firearm_model_x,firearm_caliber_x,recovery_date_x,recovery_block_address_x,city_x,state_x,...,person_recovered_from_sex_y,person_recovered_from_age_y,address_concat,longitude,latitude,confidence,source,recovery_block_address_y,x,y
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,...,M,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN
2,80-08-008343,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,...,M,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN
3,80-08-047627,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,...,M,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,...,M,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,Wpns Law Violation,NaN,"Glock, Inc. ...",Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,...,M,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN
23657,80-17-014942,Narcotics,"Pistol, Semi-Automatic ...",Cobra Enterprises Inc ...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,...,F,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN
23658,80-17-015000,Wpns Law Violation,"Pistol, Semi-Automatic ...","Glock, Inc. ...",,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,...,M,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN
23659,80-17-015225,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23660,80-17-015302,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN

In [34]:
firearm_data = firearm_data.drop_duplicates()

In [35]:
firearm_data

,incident_number,ucr_category_x,type_of_firearm_x,firearm_manufacturer_x,firearm_model_x,firearm_caliber_x,recovery_date_x,recovery_block_address_x,city_x,state_x,...,person_recovered_from_sex_y,person_recovered_from_age_y,address_concat,longitude,latitude,confidence,source,recovery_block_address_y,x,y
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,...,M,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN
2,80-08-008343,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,...,M,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN
3,80-08-047627,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,...,M,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,...,M,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,Wpns Law Violation,NaN,"Glock, Inc. ...",Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,...,M,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN
23657,80-17-014942,Narcotics,"Pistol, Semi-Automatic ...",Cobra Enterprises Inc ...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,...,F,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN
23658,80-17-015000,Wpns Law Violation,"Pistol, Semi-Automatic ...","Glock, Inc. ...",,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,...,M,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN
23659,80-17-015225,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23660,80-17-015302,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN

## Looking at our newly merged dataset

This is our completed dataset. Now, we can go ahead and take a look at our columns.

In [36]:
firearm_data.columns

Index(['incident_number', 'ucr_category_x', 'type_of_firearm_x',
       'firearm_manufacturer_x', 'firearm_model_x', 'firearm_caliber_x',
       'recovery_date_x', 'recovery_block_address_x', 'city_x', 'state_x',
       'recovery_zipcode_x', 'person_recovered_from_race_x',
       'person_recovered_from_sex_x', 'person_recovered_from_age_x', 'year',
       'ucr_category_y', 'type_of_firearm_y', 'firearm_manufacturer_y',
       'firearm_model_y', 'firearm_caliber_y', 'recovery_date_y',
       'address_geocode_type', 'recovery_address', 'city_y', 'state_y',
       'recovery_zipcode_y', 'person_recovered_from_race_y',
       'person_recovered_from_sex_y', 'person_recovered_from_age_y',
       'address_concat', 'longitude', 'latitude', 'confidence', 'source',
       'recovery_block_address_y', 'x', 'y'],
      dtype='object')

In [37]:
firearm_data.dtypes

incident_number                  object
ucr_category_x                   object
type_of_firearm_x                object
firearm_manufacturer_x           object
firearm_model_x                  object
firearm_caliber_x                object
recovery_date_x                  object
recovery_block_address_x         object
city_x                           object
state_x                          object
recovery_zipcode_x               object
person_recovered_from_race_x     object
person_recovered_from_sex_x      object
person_recovered_from_age_x     float64
year                            float64
ucr_category_y                   object
type_of_firearm_y                object
firearm_manufacturer_y           object
firearm_model_y                  object
firearm_caliber_y                object
recovery_date_y                  object
address_geocode_type             object
recovery_address                 object
city_y                           object
state_y                          object
recovery_zipcode_y              float64
person_recovered_from_race_y     object
person_recovered_from_sex_y      object
person_recovered_from_age_y     float64
address_concat                   object
longitude                       float64
latitude                        float64
confidence                      float64
source                           object
recovery_block_address_y         object
x                               float64
y                               float64
dtype: object

### Checking Split Columns for Duplicates

We have a TON of repeated columns here. I want to go ahead and make sure that the repeated columns aren't the same before I decide what to do with them.

In [38]:
print("ucr_category: "+ str(firearm_data['ucr_category_x'].equals(firearm_data['ucr_category_y'])))
print("type_of_firearm: " + str(firearm_data['type_of_firearm_x'].equals(firearm_data['type_of_firearm_y'])))
print("firearm_manufacturer: " + str(firearm_data['firearm_manufacturer_x'].equals(firearm_data['firearm_manufacturer_y'])))
print("firearm_model: " + str(firearm_data['firearm_model_x'].equals(firearm_data['firearm_model_y'])))
print("firearm_caliber: " + str(firearm_data['firearm_caliber_x'].equals(firearm_data['firearm_caliber_y'])))
print("recovery_date: " + str(firearm_data['recovery_date_x'].equals(firearm_data['recovery_date_y'])))
print("recovery_block_address: " + str(firearm_data['recovery_block_address_x'].equals(firearm_data['recovery_block_address_y'])))
print("city: " + str(firearm_data['city_x'].equals(firearm_data['city_y'])))
print("state: " + str(firearm_data['state_x'].equals(firearm_data['state_y'])))
print("recovery_zipcode: " + str(firearm_data['recovery_zipcode_x'].equals(firearm_data['recovery_zipcode_y'])))
print("person_recovered_from_race: " + str(firearm_data['person_recovered_from_race_x'].equals(firearm_data['person_recovered_from_race_y'])))
print("person_recovered_from_sex: " + str(firearm_data['person_recovered_from_sex_x'].equals(firearm_data['person_recovered_from_sex_y'])))
print("person_recovered_from_age: " + str(firearm_data['person_recovered_from_age_x'].equals(firearm_data['person_recovered_from_age_y'])))

ucr_category: False
type_of_firearm: False
firearm_manufacturer: False
firearm_model: False
firearm_caliber: False
recovery_date: False
recovery_block_address: False
city: False
state: False
recovery_zipcode: False
person_recovered_from_race: False
person_recovered_from_sex: False
person_recovered_from_age: False

So basically, none of these columns are the same. Can we merge them without overlapping values?

In [39]:
test_set = firearm_data

In [40]:
test_set

,incident_number,ucr_category_x,type_of_firearm_x,firearm_manufacturer_x,firearm_model_x,firearm_caliber_x,recovery_date_x,recovery_block_address_x,city_x,state_x,...,person_recovered_from_sex_y,person_recovered_from_age_y,address_concat,longitude,latitude,confidence,source,recovery_block_address_y,x,y
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,...,M,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN
2,80-08-008343,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,...,M,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN
3,80-08-047627,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,...,M,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,...,M,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,Wpns Law Violation,NaN,"Glock, Inc. ...",Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,...,M,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN
23657,80-17-014942,Narcotics,"Pistol, Semi-Automatic ...",Cobra Enterprises Inc ...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,...,F,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN
23658,80-17-015000,Wpns Law Violation,"Pistol, Semi-Automatic ...","Glock, Inc. ...",,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,...,M,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN
23659,80-17-015225,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23660,80-17-015302,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN

In [41]:
test_set['ucr_category'] = test_set.ucr_category_x.combine_first(test_set.ucr_category_y)

In [42]:
test_set

,incident_number,ucr_category_x,type_of_firearm_x,firearm_manufacturer_x,firearm_model_x,firearm_caliber_x,recovery_date_x,recovery_block_address_x,city_x,state_x,...,person_recovered_from_age_y,address_concat,longitude,latitude,confidence,source,recovery_block_address_y,x,y,ucr_category
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN,Homicide
1,80-06-108219,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,...,38.0,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,NaN,NaN,Burglary
2,80-08-008343,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,...,30.0,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,NaN,NaN,Burglary
3,80-08-047627,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,...,25.0,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,NaN,NaN,Aggravated Assault
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,...,15.0,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,NaN,NaN,Theft Fr Veh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,Wpns Law Violation,NaN,"Glock, Inc. ...",Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,...,24.0,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,NaN,NaN,Wpns Law Violation
23657,80-17-014942,Narcotics,"Pistol, Semi-Automatic ...",Cobra Enterprises Inc ...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,...,19.0,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,NaN,NaN,Narcotics
23658,80-17-015000,Wpns Law Violation,"Pistol, Semi-Automatic ...","Glock, Inc. ...",,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,...,32.0,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,NaN,NaN,Wpns Law Violation
23659,80-17-015225,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wpns Law Violation
23660,80-17-015302,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,NaN,NaN,0.000000,0.000000,0.00,none,NaN,NaN,NaN,Suicide

In [43]:
test_set_save = pd.DataFrame(test_set[['ucr_category', 'ucr_category_x', 'ucr_category_y']])

In [44]:
test_set_save

             ucr_category      ucr_category_x      ucr_category_y
0                Homicide            Homicide            Homicide
1                Burglary            Burglary            Burglary
2                Burglary            Burglary            Burglary
3      Aggravated Assault  Aggravated Assault  Aggravated Assault
4            Theft Fr Veh        Theft Fr Veh        Theft Fr Veh
...                   ...                 ...                 ...
23656  Wpns Law Violation  Wpns Law Violation  Wpns Law Violation
23657           Narcotics           Narcotics           Narcotics
23658  Wpns Law Violation  Wpns Law Violation  Wpns Law Violation
23659  Wpns Law Violation  Wpns Law Violation                 NaN
23660             Suicide             Suicide             Suicide

[23661 rows x 3 columns]

In [45]:
test_set_save.sample(30)

              ucr_category       ucr_category_x       ucr_category_y
16271      Stolen Property      Stolen Property      Stolen Property
858               Burglary             Burglary             Burglary
10052            Narcotics            Narcotics            Narcotics
20519  Accidental Shooting  Accidental Shooting  Accidental Shooting
12640              Robbery              Robbery              Robbery
12955   Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
7625    Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
19398            Narcotics            Narcotics            Narcotics
1843    Aggravated Assault   Aggravated Assault   Aggravated Assault
22272            Narcotics            Narcotics            Narcotics
1237    Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
23123            Narcotics            Narcotics            Narcotics
21335      Stolen Property      Stolen Property                  NaN
4052             Narcotics            Narcotics            Narcotics
22349            Narcotics            Narcotics            Narcotics
6656       Stolen Property      Stolen Property      Stolen Property
20483   Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
22311            Narcotics            Narcotics            Narcotics
3993             Narcotics            Narcotics            Narcotics
9602    Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
18973            Narcotics            Narcotics            Narcotics
11088   Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
2949    Aggravated Assault   Aggravated Assault   Aggravated Assault
15151            Narcotics            Narcotics            Narcotics
16724   Aggravated Assault   Aggravated Assault   Aggravated Assault
22714            Narcotics            Narcotics            Narcotics
1310               Robbery              Robbery              Robbery
4174             Narcotics            Narcotics            Narcotics
12654   Wpns Law Violation   Wpns Law Violation   Wpns Law Violation
142              Narcotics            Narcotics            Narcotics

### Merging Our Duplicate Columns

After taking a random sample of 30 values, it seems our values were merged the way we wanted them to be. I'm going to create a function so we can do this a bit easier for each column.

In [46]:
def merge_column(dataFrame, columnName):
    column_x = (columnName + '_x')
    column_y = (columnName + '_y')
    dataFrame[columnName] = dataFrame[column_x].combine_first(dataFrame[column_y])

In [47]:
firearm_data.columns

Index(['incident_number', 'ucr_category_x', 'type_of_firearm_x',
       'firearm_manufacturer_x', 'firearm_model_x', 'firearm_caliber_x',
       'recovery_date_x', 'recovery_block_address_x', 'city_x', 'state_x',
       'recovery_zipcode_x', 'person_recovered_from_race_x',
       'person_recovered_from_sex_x', 'person_recovered_from_age_x', 'year',
       'ucr_category_y', 'type_of_firearm_y', 'firearm_manufacturer_y',
       'firearm_model_y', 'firearm_caliber_y', 'recovery_date_y',
       'address_geocode_type', 'recovery_address', 'city_y', 'state_y',
       'recovery_zipcode_y', 'person_recovered_from_race_y',
       'person_recovered_from_sex_y', 'person_recovered_from_age_y',
       'address_concat', 'longitude', 'latitude', 'confidence', 'source',
       'recovery_block_address_y', 'x', 'y', 'ucr_category'],
      dtype='object')

In [48]:
merge_column(firearm_data, 'ucr_category')
merge_column(firearm_data, 'type_of_firearm')
merge_column(firearm_data, 'firearm_manufacturer')
merge_column(firearm_data, 'firearm_model')
merge_column(firearm_data, 'firearm_caliber')
merge_column(firearm_data, 'recovery_date')
merge_column(firearm_data, 'recovery_block_address')
merge_column(firearm_data, 'city')
merge_column(firearm_data, 'state')
merge_column(firearm_data, 'recovery_zipcode')
merge_column(firearm_data, 'person_recovered_from_race')
merge_column(firearm_data, 'person_recovered_from_sex')
merge_column(firearm_data, 'person_recovered_from_age')

In [49]:
firearm_data

,incident_number,ucr_category_x,type_of_firearm_x,firearm_manufacturer_x,firearm_model_x,firearm_caliber_x,recovery_date_x,recovery_block_address_x,city_x,state_x,...,firearm_model,firearm_caliber,recovery_date,recovery_block_address,city,state,recovery_zipcode,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age
0,80-06-008380,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,Null,NaN,NaN,NaN,Louisville,KY,40202,Null,NaN,NaN
1,80-06-108219,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,40272,White,M,38.0
2,80-08-008343,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,40216,Black,M,30.0
3,80-08-047627,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,40210,Black,M,25.0
4,80-08-091695,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,40203,White,M,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,Wpns Law Violation,NaN,"Glock, Inc. ...",Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,...,Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,40202,Black,M,24.0
23657,80-17-014942,Narcotics,"Pistol, Semi-Automatic ...",Cobra Enterprises Inc ...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,40214,Black,F,19.0
23658,80-17-015000,Wpns Law Violation,"Pistol, Semi-Automatic ...","Glock, Inc. ...",,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,...,,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,40214,White,M,32.0
23659,80-17-015225,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,40272,White,M,19.0
23660,80-17-015302,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,Louisville,KY,...,Null,NaN,NaN,NaN,Louisville,KY,40210,Null,NaN,NaN

### Dropping our extra columns and duplicate rows after our final merge

In [50]:
firearm_data = firearm_data.loc[:, ~firearm_data.columns.str.endswith('_x')]

In [51]:
firearm_data = firearm_data.loc[:, ~firearm_data.columns.str.endswith('_y')]

In [52]:
firearm_data

,incident_number,year,address_geocode_type,recovery_address,address_concat,longitude,latitude,confidence,source,x,...,firearm_model,firearm_caliber,recovery_date,recovery_block_address,city,state,recovery_zipcode,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age
0,80-06-008380,NaN,NO ADDRESS,Null,NaN,0.000000,0.000000,0.00,none,NaN,...,Null,NaN,NaN,NaN,Louisville,KY,40202,Null,NaN,NaN
1,80-06-108219,2014.0,BLOCK,4700 Haney Way,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,40272,White,M,38.0
2,80-08-008343,2010.0,BLOCK,3400 Shagbark Rd,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,40216,Black,M,30.0
3,80-08-047627,2012.0,BLOCK,1700 W Hill St,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,40210,Black,M,25.0
4,80-08-091695,2008.0,BLOCK,1000 Cladwell,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,40203,White,M,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017.0,BLOCK,600 W Jefferson St,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,...,Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,40202,Black,M,24.0
23657,80-17-014942,2017.0,BLOCK,4200 S 2nd St,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,40214,Black,F,19.0
23658,80-17-015000,2017.0,BLOCK,4500 S 6th St,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,...,,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,40214,White,M,32.0
23659,80-17-015225,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,40272,White,M,19.0
23660,80-17-015302,NaN,NO ADDRESS,Null,NaN,0.000000,0.000000,0.00,none,NaN,...,Null,NaN,NaN,NaN,Louisville,KY,40210,Null,NaN,NaN

In [53]:
firearm_data = firearm_data.drop_duplicates()

In [54]:
firearm_data

,incident_number,year,address_geocode_type,recovery_address,address_concat,longitude,latitude,confidence,source,x,...,firearm_model,firearm_caliber,recovery_date,recovery_block_address,city,state,recovery_zipcode,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age
0,80-06-008380,NaN,NO ADDRESS,Null,NaN,0.000000,0.000000,0.00,none,NaN,...,Null,NaN,NaN,NaN,Louisville,KY,40202,Null,NaN,NaN
1,80-06-108219,2014.0,BLOCK,4700 Haney Way,4700 Haney Way Louisville KY 40272,-85.850950,38.096623,1.00,openaddresses,NaN,...,Modle 25 Series,,7/30/2014,4700 Block Haney Way ...,Louisville,KY,40272,White,M,38.0
2,80-08-008343,2010.0,BLOCK,3400 Shagbark Rd,3400 Shagbark Rd Louisville KY 40216,-85.843407,38.196532,1.00,openaddresses,NaN,...,Jennings Firear,380C,1/20/2010,3400 Block Shagbark Rd ...,Louisville,KY,40216,Black,M,30.0
3,80-08-047627,2012.0,BLOCK,1700 W Hill St,1700 W Hill St Louisville KY 40210,-85.784928,38.227766,1.00,openaddresses,NaN,...,,9MM,6/18/2012,1700 Block W Hill St ...,Louisville,KY,40210,Black,M,25.0
4,80-08-091695,2008.0,BLOCK,1000 Cladwell,1000 Cladwell Louisville KY 40203,-85.757053,38.238555,0.67,openaddresses,NaN,...,E28,25C,11/29/2008,1000 Block Cladwell ...,Louisville,KY,40203,White,M,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017.0,BLOCK,600 W Jefferson St,600 W Jefferson St Louisville KY 40202,-85.761323,38.253961,1.00,openaddresses,NaN,...,Model 31/31C (3,,2/21/2017,600 Block W Jefferson St ...,Louisville,KY,40202,Black,M,24.0
23657,80-17-014942,2017.0,BLOCK,4200 S 2nd St,4200 S 2nd St Louisville KY 40214,-85.763628,38.195203,1.00,openaddresses,NaN,...,Ca Series,380C,2/21/2017,4200 Block S 2Nd St ...,Louisville,KY,40214,Black,F,19.0
23658,80-17-015000,2017.0,BLOCK,4500 S 6th St,4500 S 6th St Louisville KY 40214,-85.770469,38.188165,1.00,openaddresses,NaN,...,,45C,2/21/2017,4500 Block S 6Th St ...,Louisville,KY,40214,White,M,32.0
23659,80-17-015225,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,9MM,2/22/2017,Dixie Hwy At I265 ...,Louisville,KY,40272,White,M,19.0
23660,80-17-015302,NaN,NO ADDRESS,Null,NaN,0.000000,0.000000,0.00,none,NaN,...,Null,NaN,NaN,NaN,Louisville,KY,40210,Null,NaN,NaN

### Reordering Columns

In [55]:
firearm_data.columns

Index(['incident_number', 'year', 'address_geocode_type', 'recovery_address',
       'address_concat', 'longitude', 'latitude', 'confidence', 'source', 'x',
       'y', 'ucr_category', 'type_of_firearm', 'firearm_manufacturer',
       'firearm_model', 'firearm_caliber', 'recovery_date',
       'recovery_block_address', 'city', 'state', 'recovery_zipcode',
       'person_recovered_from_race', 'person_recovered_from_sex',
       'person_recovered_from_age'],
      dtype='object')

In [56]:
firearm_data = firearm_data[["incident_number", "year", "recovery_date", "ucr_category", "type_of_firearm", "firearm_manufacturer", "firearm_model", "firearm_caliber", "address_concat", "address_geocode_type", "recovery_block_address", "recovery_address", "city", "state", "recovery_zipcode", "longitude", "latitude", "x", "y", "person_recovered_from_race", "person_recovered_from_sex", "person_recovered_from_age", "confidence", "source"]]

In [57]:
firearm_data.head()

,incident_number,year,recovery_date,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,address_concat,address_geocode_type,...,recovery_zipcode,longitude,latitude,x,y,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence,source
0,80-06-008380,NaN,NaN,Homicide,Null,Null,Null,NaN,NaN,NO ADDRESS,...,40202,0.000000,0.000000,NaN,NaN,Null,NaN,NaN,0.00,none
1,80-06-108219,2014.0,7/30/2014,Burglary,"Rifle, Single-Shot ...",Marlin Firearms Co. ...,Modle 25 Series,,4700 Haney Way Louisville KY 40272,BLOCK,...,40272,-85.850950,38.096623,NaN,NaN,White,M,38.0,1.00,openaddresses
2,80-08-008343,2010.0,1/20/2010,Burglary,"Pistol, Semi-Automatic ...",Jennings Firear ...,Jennings Firear,380C,3400 Shagbark Rd Louisville KY 40216,BLOCK,...,40216,-85.843407,38.196532,NaN,NaN,Black,M,30.0,1.00,openaddresses
3,80-08-047627,2012.0,6/18/2012,Aggravated Assault,"Pistol, Semi-Automatic ...",Parabellum ...,,9MM,1700 W Hill St Louisville KY 40210,BLOCK,...,40210,-85.784928,38.227766,NaN,NaN,Black,M,25.0,1.00,openaddresses
4,80-08-091695,2008.0,11/29/2008,Theft Fr Veh,"Pistol, Semi-Automatic ...",Fie ...,E28,25C,1000 Cladwell Louisville KY 40203,BLOCK,...,40203,-85.757053,38.238555,NaN,NaN,White,M,15.0,0.67,openaddresses

In [58]:
firearm_data.describe()

,year,longitude,latitude,x,y,person_recovered_from_age,confidence
count,11263.000000,8803.000000,8803.000000,1.361000e+03,1361.000000,9140.000000,8803.000000
mean,2013.501998,-79.447296,35.389723,1.207515e+06,261510.687991,30.599562,0.813746
std,2.117481,22.427429,9.988813,1.917131e+04,17402.523667,12.308569,0.290693
min,2008.000000,-122.440321,0.000000,1.166337e+06,206744.500000,0.000000,0.000000
25%,2012.000000,-85.789370,38.167984,1.195536e+06,251281.062500,21.000000,0.664000
50%,2014.000000,-85.761323,38.229139,1.204016e+06,267058.187500,27.000000,1.000000
75%,2015.000000,-85.690866,38.253961,1.214921e+06,275068.000000,37.000000,1.000000
max,2017.000000,0.000000,43.199428,1.287586e+06,297530.375000,87.000000,1.000000

## Cleaning Usable Data

### Dropping Values we don't need

In [59]:
firearm_data.columns

Index(['incident_number', 'year', 'recovery_date', 'ucr_category',
       'type_of_firearm', 'firearm_manufacturer', 'firearm_model',
       'firearm_caliber', 'address_concat', 'address_geocode_type',
       'recovery_block_address', 'recovery_address', 'city', 'state',
       'recovery_zipcode', 'longitude', 'latitude', 'x', 'y',
       'person_recovered_from_race', 'person_recovered_from_sex',
       'person_recovered_from_age', 'confidence', 'source'],
      dtype='object')

In [60]:
firearm_data.drop(firearm_data[['x', 'y', 'source', 'address_concat']], axis = 1, inplace = True)

C:\Users\chris\AppData\Local\Temp\ipykernel_18812\904289819.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firearm_data.drop(firearm_data[['x', 'y', 'source', 'address_concat']], axis = 1, inplace = True)

In [61]:
firearm_data.columns

Index(['incident_number', 'year', 'recovery_date', 'ucr_category',
       'type_of_firearm', 'firearm_manufacturer', 'firearm_model',
       'firearm_caliber', 'address_geocode_type', 'recovery_block_address',
       'recovery_address', 'city', 'state', 'recovery_zipcode', 'longitude',
       'latitude', 'person_recovered_from_race', 'person_recovered_from_sex',
       'person_recovered_from_age', 'confidence'],
      dtype='object')

### Changing the Data Types

In [62]:
firearm_data.dtypes

incident_number                object
year                          float64
recovery_date                  object
ucr_category                   object
type_of_firearm                object
firearm_manufacturer           object
firearm_model                  object
firearm_caliber                object
address_geocode_type           object
recovery_block_address         object
recovery_address               object
city                           object
state                          object
recovery_zipcode               object
longitude                     float64
latitude                      float64
person_recovered_from_race     object
person_recovered_from_sex      object
person_recovered_from_age     float64
confidence                    float64
dtype: object

In [63]:
firearm_data['recovery_date'] = pd.to_datetime(firearm_data.recovery_date)

C:\Users\chris\AppData\Local\Temp\ipykernel_18812\2823338765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firearm_data['recovery_date'] = pd.to_datetime(firearm_data.recovery_date)

In [64]:
firearm_data.dtypes

incident_number                       object
year                                 float64
recovery_date                 datetime64[ns]
ucr_category                          object
type_of_firearm                       object
firearm_manufacturer                  object
firearm_model                         object
firearm_caliber                       object
address_geocode_type                  object
recovery_block_address                object
recovery_address                      object
city                                  object
state                                 object
recovery_zipcode                      object
longitude                            float64
latitude                             float64
person_recovered_from_race            object
person_recovered_from_sex             object
person_recovered_from_age            float64
confidence                           float64
dtype: object

### Separating the gun type with the subcategory

In [65]:
firearm_data['type_of_firearm'].unique()

array(['Null', 'Rifle, Single-Shot                                     ',
       'Pistol, Semi-Automatic                                 ',
       'Pistol, Revolver                                       ',
       'Shotgun, Pump Action                                   ',
       'Rifle, Automatic                                       ',
       'Shotgun, Pump Action', 'Pistol, Semi-automatic',
       'Airgun                                                 ',
       'Rifle, Bolt Action                                     ',
       'Rifle, Semi-Automatic                                  ',
       'Electronic Control Weapon                              ',
       'Pistol, Percussion                                     ',
       'Rifle, Percussion                                      ',
       'Pistol, Derringer                                      ',
       'Shotgun, Single-Shot                                   ',
       'Shotgun, Bolt Action                                   ', nan,
       'Rifle, Flintlock                                       ',
       'Rifle, Pump Action                                     ',
       'Pistol, Single-Shot                                    ',
       'Pistol, Bolt Action                                    ',
       'Submachine Gun (Machine Pistol)                        ',
       'Rifle, Semi-automatic', 'Rifle, Bolt Action',
       'Rifle, Lever Action                                    ',
       'Rifle, Carbine                                         ',
       'Machine Gun                                            ',
       'Rifle, Single-shot',
       'Shotgun, Double Barrel                                 ',
       'Shotgun, Semiautomatic                                 ',
       'Pistol, Jet Propelled                                  ',
       'Pistol, Revolver', 'Rifle, Flintlock',
       'Shotgun, Over And Under                                ',
       'Rifle, Lever Action', 'Pistol, Single-shot',
       'Shotgun, Single-shot',
       'Rifle-Shotgun Combination                              ',
       'Pistol, Flintlock                                      ',
       'Shotgun, Semiautomatic', 'Rifle, Carbine', 'Rifle, Percussion',
       'Shotgun, Double Barrel', 'Submachine Gun (machine Pistol)'],
      dtype=object)

In [66]:
firearm_data[['firearm_category', 'firearm_subcategory']] = firearm_data.type_of_firearm.str.split(",", expand = True)

C:\Users\chris\AppData\Local\Temp\ipykernel_18812\1680741139.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firearm_data[['firearm_category', 'firearm_subcategory']] = firearm_data.type_of_firearm.str.split(",", expand = True)
C:\Users\chris\AppData\Local\Temp\ipykernel_18812\1680741139.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firearm_data[['firearm_category', 'firearm_subcategory']] = firearm_data.type_of_firearm.str.split(",", expand = True)

In [67]:
firearm_data.sample(5)

,incident_number,year,recovery_date,ucr_category,type_of_firearm,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,recovery_block_address,...,state,recovery_zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence,firearm_category,firearm_subcategory
2280,80-11-004065,2011.0,2011-01-16,Vandalism,"Pistol, Revolver ...",Iver Johnson Ar ...,,38C,BLOCK,600 Block W Jefferson St ...,...,KY,40202,-85.761323,38.253961,Black,M,19.0,1.0,Pistol,Revolver
125,80-10-004471,2010.0,NaT,Suicide,Null,Null,Null,NaN,NO ADDRESS,NaN,...,KY,40207,0.000000,0.000000,Null,NaN,NaN,0.0,Null,None
5399,80-12-018351,2012.0,2012-03-08,Robbery,"Pistol, Semi-Automatic ...",Jennings Firear ...,,380C,BLOCK,1700 Block Bolling Ave ...,...,KY,40210,-85.784823,38.228748,Black,M,20.0,1.0,Pistol,Semi-Automatic
19067,80-16-034529,2016.0,2016-04-24,Stolen Property,"Pistol, Semi-Automatic ...",Hipoint ...,,9MM,NaN,W Muhammad Ali Blvd ...,...,KY,40212,NaN,NaN,Black,M,31.0,NaN,Pistol,Semi-Automatic
12823,80-14-060634,2014.0,2014-08-13,Wpns Law Violation,"Pistol, Semi-Automatic ...",Ruger ...,Handguns: Lcp S,380C,BLOCK,8700 Block Running Fox Cir ...,...,KY,40291,-85.601180,38.149303,White,M,28.0,1.0,Pistol,Semi-Automatic

In [68]:
firearm_data.drop(firearm_data[['type_of_firearm']], axis=1, inplace = True)

C:\Users\chris\AppData\Local\Temp\ipykernel_18812\2313111858.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  firearm_data.drop(firearm_data[['type_of_firearm']], axis=1, inplace = True)

In [69]:
firearm_data.columns

Index(['incident_number', 'year', 'recovery_date', 'ucr_category',
       'firearm_manufacturer', 'firearm_model', 'firearm_caliber',
       'address_geocode_type', 'recovery_block_address', 'recovery_address',
       'city', 'state', 'recovery_zipcode', 'longitude', 'latitude',
       'person_recovered_from_race', 'person_recovered_from_sex',
       'person_recovered_from_age', 'confidence', 'firearm_category',
       'firearm_subcategory'],
      dtype='object')

In [70]:
firearm_data = firearm_data[["incident_number", 
                             "year", 
                             "recovery_date", 
                             "ucr_category", 
                             "firearm_category", 
                             "firearm_subcategory", 
                             "firearm_manufacturer", 
                             "firearm_model", 
                             "firearm_caliber", 
                             "address_geocode_type", 
                             "recovery_block_address",
                             "recovery_address",
                             "city",
                             "state",
                             "recovery_zipcode",
                             "longitude", 
                             "latitude", 
                             "person_recovered_from_race", 
                             "person_recovered_from_sex", 
                             "person_recovered_from_age", 
                             "confidence"]]

### Making consistent N/A Values

In [71]:
firearm_data = firearm_data.replace('Null', np.NaN)
firearm_data = firearm_data.replace('NO ADDRESS', np.NaN)
firearm_data = firearm_data.replace('', np.NaN)
firearm_data = firearm_data.replace(' ', np.NaN)
firearm_data = firearm_data.fillna(np.NaN)

In [72]:
firearm_data

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,recovery_address,city,state,recovery_zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
0,80-06-008380,NaN,NaT,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40202,0.000000,0.000000,NaN,NaN,NaN,0.00
1,80-06-108219,2014.0,2014-07-30,Burglary,Rifle,Single-Shot,Marlin Firearms Co. ...,Modle 25 Series,,BLOCK,...,4700 Haney Way,Louisville,KY,40272,-85.850950,38.096623,White,M,38.0,1.00
2,80-08-008343,2010.0,2010-01-20,Burglary,Pistol,Semi-Automatic,Jennings Firear ...,Jennings Firear,380C,BLOCK,...,3400 Shagbark Rd,Louisville,KY,40216,-85.843407,38.196532,Black,M,30.0,1.00
3,80-08-047627,2012.0,2012-06-18,Aggravated Assault,Pistol,Semi-Automatic,Parabellum ...,,9MM,BLOCK,...,1700 W Hill St,Louisville,KY,40210,-85.784928,38.227766,Black,M,25.0,1.00
4,80-08-091695,2008.0,2008-11-29,Theft Fr Veh,Pistol,Semi-Automatic,Fie ...,E28,25C,BLOCK,...,1000 Cladwell,Louisville,KY,40203,-85.757053,38.238555,White,M,15.0,0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017.0,2017-02-21,Wpns Law Violation,NaN,NaN,"Glock, Inc. ...",Model 31/31C (3,,BLOCK,...,600 W Jefferson St,Louisville,KY,40202,-85.761323,38.253961,Black,M,24.0,1.00
23657,80-17-014942,2017.0,2017-02-21,Narcotics,Pistol,Semi-Automatic,Cobra Enterprises Inc ...,Ca Series,380C,BLOCK,...,4200 S 2nd St,Louisville,KY,40214,-85.763628,38.195203,Black,F,19.0,1.00
23658,80-17-015000,2017.0,2017-02-21,Wpns Law Violation,Pistol,Semi-Automatic,"Glock, Inc. ...",,45C,BLOCK,...,4500 S 6th St,Louisville,KY,40214,-85.770469,38.188165,White,M,32.0,1.00
23659,80-17-015225,2017.0,2017-02-22,Wpns Law Violation,Pistol,Semi-Automatic,Ruger ...,,9MM,NaN,...,NaN,Louisville,KY,40272,NaN,NaN,White,M,19.0,NaN
23660,80-17-015302,NaN,NaT,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40210,0.000000,0.000000,NaN,NaN,NaN,0.00

### Getting rid of white space around values

In [73]:
firearm_data['firearm_subcategory'].unique()

array([nan, ' Single-Shot                                     ',
       ' Semi-Automatic                                 ',
       ' Revolver                                       ',
       ' Pump Action                                   ',
       ' Automatic                                       ',
       ' Pump Action', ' Semi-automatic',
       ' Bolt Action                                     ',
       ' Semi-Automatic                                  ',
       ' Percussion                                     ',
       ' Percussion                                      ',
       ' Derringer                                      ',
       ' Single-Shot                                   ',
       ' Bolt Action                                   ',
       ' Flintlock                                       ',
       ' Pump Action                                     ',
       ' Single-Shot                                    ',
       ' Bolt Action                                    ', ' Bolt Action',
       ' Lever Action                                    ',
       ' Carbine                                         ',
       ' Single-shot', ' Double Barrel                                 ',
       ' Semiautomatic                                 ',
       ' Jet Propelled                                  ', ' Revolver',
       ' Flintlock', ' Over And Under                                ',
       ' Lever Action',
       ' Flintlock                                      ',
       ' Semiautomatic', ' Carbine', ' Percussion', ' Double Barrel'],
      dtype=object)

In [74]:
firearm_data.columns

Index(['incident_number', 'year', 'recovery_date', 'ucr_category',
       'firearm_category', 'firearm_subcategory', 'firearm_manufacturer',
       'firearm_model', 'firearm_caliber', 'address_geocode_type',
       'recovery_block_address', 'recovery_address', 'city', 'state',
       'recovery_zipcode', 'longitude', 'latitude',
       'person_recovered_from_race', 'person_recovered_from_sex',
       'person_recovered_from_age', 'confidence'],
      dtype='object')

In [75]:
def trim_space(columnName):
    firearm_data[columnName] = firearm_data[columnName].str.lstrip()
    firearm_data[columnName] = firearm_data[columnName].str.rstrip()

In [76]:
trim_space('incident_number')
trim_space('ucr_category')
trim_space('firearm_category')
trim_space('firearm_subcategory')
trim_space('firearm_manufacturer')
trim_space('firearm_model')
trim_space('firearm_caliber')
trim_space('address_geocode_type')
trim_space('recovery_block_address')
trim_space('recovery_address')
trim_space('city')
trim_space('state')
trim_space('recovery_zipcode')
trim_space('person_recovered_from_race')
trim_space('person_recovered_from_sex')

In [77]:
firearm_data.dtypes

incident_number                       object
year                                 float64
recovery_date                 datetime64[ns]
ucr_category                          object
firearm_category                      object
firearm_subcategory                   object
firearm_manufacturer                  object
firearm_model                         object
firearm_caliber                       object
address_geocode_type                  object
recovery_block_address                object
recovery_address                      object
city                                  object
state                                 object
recovery_zipcode                      object
longitude                            float64
latitude                             float64
person_recovered_from_race            object
person_recovered_from_sex             object
person_recovered_from_age            float64
confidence                           float64
dtype: object

In [78]:
firearm_data.columns = ['incident_number',
                       'year',
                       'recovery_date',
                       'ucr_category',
                       'firearm_category',
                       'firearm_subcategory',
                       'firearm_manufacturer',
                       'firearm_model',
                       'firearm_caliber',
                       'address_geocode_type',
                       'block_address',
                       'street_address',
                       'city',
                       'state',
                       'zipcode',
                       'longitude',
                       'latitude',
                       'person_recovered_from_race',
                       'person_recovered_from_sex',
                       'person_recovered_from_age',
                       'confidence']

In [79]:
firearm_data

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,street_address,city,state,zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
0,80-06-008380,NaN,NaT,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40202,0.000000,0.000000,NaN,NaN,NaN,0.00
1,80-06-108219,2014.0,2014-07-30,Burglary,Rifle,Single-Shot,Marlin Firearms Co.,Modle 25 Series,,BLOCK,...,4700 Haney Way,Louisville,KY,40272,-85.850950,38.096623,White,M,38.0,1.00
2,80-08-008343,2010.0,2010-01-20,Burglary,Pistol,Semi-Automatic,Jennings Firear,Jennings Firear,380C,BLOCK,...,3400 Shagbark Rd,Louisville,KY,40216,-85.843407,38.196532,Black,M,30.0,1.00
3,80-08-047627,2012.0,2012-06-18,Aggravated Assault,Pistol,Semi-Automatic,Parabellum,,9MM,BLOCK,...,1700 W Hill St,Louisville,KY,40210,-85.784928,38.227766,Black,M,25.0,1.00
4,80-08-091695,2008.0,2008-11-29,Theft Fr Veh,Pistol,Semi-Automatic,Fie,E28,25C,BLOCK,...,1000 Cladwell,Louisville,KY,40203,-85.757053,38.238555,White,M,15.0,0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017.0,2017-02-21,Wpns Law Violation,NaN,NaN,"Glock, Inc.",Model 31/31C (3,,BLOCK,...,600 W Jefferson St,Louisville,KY,40202,-85.761323,38.253961,Black,M,24.0,1.00
23657,80-17-014942,2017.0,2017-02-21,Narcotics,Pistol,Semi-Automatic,Cobra Enterprises Inc,Ca Series,380C,BLOCK,...,4200 S 2nd St,Louisville,KY,40214,-85.763628,38.195203,Black,F,19.0,1.00
23658,80-17-015000,2017.0,2017-02-21,Wpns Law Violation,Pistol,Semi-Automatic,"Glock, Inc.",,45C,BLOCK,...,4500 S 6th St,Louisville,KY,40214,-85.770469,38.188165,White,M,32.0,1.00
23659,80-17-015225,2017.0,2017-02-22,Wpns Law Violation,Pistol,Semi-Automatic,Ruger,,9MM,NaN,...,NaN,Louisville,KY,40272,NaN,NaN,White,M,19.0,NaN
23660,80-17-015302,NaN,NaT,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40210,0.000000,0.000000,NaN,NaN,NaN,0.00

### Cleaning Year Values

In [80]:
firearm_data['year'] = firearm_data['year'].apply(str)

In [81]:
firearm_data

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,street_address,city,state,zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
0,80-06-008380,nan,NaT,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40202,0.000000,0.000000,NaN,NaN,NaN,0.00
1,80-06-108219,2014.0,2014-07-30,Burglary,Rifle,Single-Shot,Marlin Firearms Co.,Modle 25 Series,,BLOCK,...,4700 Haney Way,Louisville,KY,40272,-85.850950,38.096623,White,M,38.0,1.00
2,80-08-008343,2010.0,2010-01-20,Burglary,Pistol,Semi-Automatic,Jennings Firear,Jennings Firear,380C,BLOCK,...,3400 Shagbark Rd,Louisville,KY,40216,-85.843407,38.196532,Black,M,30.0,1.00
3,80-08-047627,2012.0,2012-06-18,Aggravated Assault,Pistol,Semi-Automatic,Parabellum,,9MM,BLOCK,...,1700 W Hill St,Louisville,KY,40210,-85.784928,38.227766,Black,M,25.0,1.00
4,80-08-091695,2008.0,2008-11-29,Theft Fr Veh,Pistol,Semi-Automatic,Fie,E28,25C,BLOCK,...,1000 Cladwell,Louisville,KY,40203,-85.757053,38.238555,White,M,15.0,0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017.0,2017-02-21,Wpns Law Violation,NaN,NaN,"Glock, Inc.",Model 31/31C (3,,BLOCK,...,600 W Jefferson St,Louisville,KY,40202,-85.761323,38.253961,Black,M,24.0,1.00
23657,80-17-014942,2017.0,2017-02-21,Narcotics,Pistol,Semi-Automatic,Cobra Enterprises Inc,Ca Series,380C,BLOCK,...,4200 S 2nd St,Louisville,KY,40214,-85.763628,38.195203,Black,F,19.0,1.00
23658,80-17-015000,2017.0,2017-02-21,Wpns Law Violation,Pistol,Semi-Automatic,"Glock, Inc.",,45C,BLOCK,...,4500 S 6th St,Louisville,KY,40214,-85.770469,38.188165,White,M,32.0,1.00
23659,80-17-015225,2017.0,2017-02-22,Wpns Law Violation,Pistol,Semi-Automatic,Ruger,,9MM,NaN,...,NaN,Louisville,KY,40272,NaN,NaN,White,M,19.0,NaN
23660,80-17-015302,nan,NaT,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40210,0.000000,0.000000,NaN,NaN,NaN,0.00

In [82]:
firearm_data[['year', 'nil']] = firearm_data['year'].str.split(".", n=1, expand = True)

In [83]:
firearm_data.drop(firearm_data[['nil']], axis=1, inplace = True)

In [84]:
firearm_data['year'].unique()

array(['nan', '2014', '2010', '2012', '2008', '2009', '2015', '2011',
       '2016', '2013', '2017'], dtype=object)

In [85]:
firearm_data['year'] = firearm_data['year'].replace('nan', np.NaN)
firearm_data['year'] = firearm_data['year'].replace('', np.NaN)
firearm_data['year'] = firearm_data['year'].replace(' ', np.NaN)
firearm_data['year'] = firearm_data['year'].replace('0', np.NaN)

In [86]:
firearm_data['year'].unique()

array([nan, '2014', '2010', '2012', '2008', '2009', '2015', '2011',
       '2016', '2013', '2017'], dtype=object)

In [87]:
firearm_data

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,street_address,city,state,zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
0,80-06-008380,NaN,NaT,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40202,0.000000,0.000000,NaN,NaN,NaN,0.00
1,80-06-108219,2014,2014-07-30,Burglary,Rifle,Single-Shot,Marlin Firearms Co.,Modle 25 Series,,BLOCK,...,4700 Haney Way,Louisville,KY,40272,-85.850950,38.096623,White,M,38.0,1.00
2,80-08-008343,2010,2010-01-20,Burglary,Pistol,Semi-Automatic,Jennings Firear,Jennings Firear,380C,BLOCK,...,3400 Shagbark Rd,Louisville,KY,40216,-85.843407,38.196532,Black,M,30.0,1.00
3,80-08-047627,2012,2012-06-18,Aggravated Assault,Pistol,Semi-Automatic,Parabellum,,9MM,BLOCK,...,1700 W Hill St,Louisville,KY,40210,-85.784928,38.227766,Black,M,25.0,1.00
4,80-08-091695,2008,2008-11-29,Theft Fr Veh,Pistol,Semi-Automatic,Fie,E28,25C,BLOCK,...,1000 Cladwell,Louisville,KY,40203,-85.757053,38.238555,White,M,15.0,0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017,2017-02-21,Wpns Law Violation,NaN,NaN,"Glock, Inc.",Model 31/31C (3,,BLOCK,...,600 W Jefferson St,Louisville,KY,40202,-85.761323,38.253961,Black,M,24.0,1.00
23657,80-17-014942,2017,2017-02-21,Narcotics,Pistol,Semi-Automatic,Cobra Enterprises Inc,Ca Series,380C,BLOCK,...,4200 S 2nd St,Louisville,KY,40214,-85.763628,38.195203,Black,F,19.0,1.00
23658,80-17-015000,2017,2017-02-21,Wpns Law Violation,Pistol,Semi-Automatic,"Glock, Inc.",,45C,BLOCK,...,4500 S 6th St,Louisville,KY,40214,-85.770469,38.188165,White,M,32.0,1.00
23659,80-17-015225,2017,2017-02-22,Wpns Law Violation,Pistol,Semi-Automatic,Ruger,,9MM,NaN,...,NaN,Louisville,KY,40272,NaN,NaN,White,M,19.0,NaN
23660,80-17-015302,NaN,NaT,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40210,0.000000,0.000000,NaN,NaN,NaN,0.00

### Cleaning incident number values

In [88]:
firearm_data['incident_number'].unique()

array(['80-06-008380', '80-06-108219', '80-08-008343', ...,
       '80-17-015000', '80-17-015225', '80-17-015302'], dtype=object)

In [89]:
firearm_data['incident_number'] = firearm_data['incident_number'].replace('', np.NaN)
firearm_data['incident_number'] = firearm_data['incident_number'].replace(' ', np.NaN)

In [90]:
firearm_data['incident_number'].unique()

array(['80-06-008380', '80-06-108219', '80-08-008343', ...,
       '80-17-015000', '80-17-015225', '80-17-015302'], dtype=object)

### Cleaning recovery date values

In [91]:
firearm_data['recovery_date'].unique()

<DatetimeArray>
[                'NaT', '2014-07-30 00:00:00', '2010-01-20 00:00:00',
 '2012-06-18 00:00:00', '2008-11-29 00:00:00', '2014-02-24 00:00:00',
 '2010-05-14 00:00:00', '2010-01-07 00:00:00', '2009-12-29 00:00:00',
 '2010-01-01 00:00:00',
 ...
 '2017-02-11 00:00:00', '2017-02-12 00:00:00', '2017-02-13 00:00:00',
 '2017-02-14 00:00:00', '2017-02-15 00:00:00', '2017-02-16 00:00:00',
 '2017-02-17 00:00:00', '2017-02-19 00:00:00', '2017-02-20 00:00:00',
 '2017-02-21 00:00:00']
Length: 2427, dtype: datetime64[ns]

In [92]:
firearm_data['recovery_date'] = firearm_data['recovery_date'].replace('', np.NaN)
firearm_data['recovery_date'] = firearm_data['recovery_date'].replace(' ', np.NaN)

In [93]:
firearm_data['recovery_date'].unique()

<DatetimeArray>
[                'NaT', '2014-07-30 00:00:00', '2010-01-20 00:00:00',
 '2012-06-18 00:00:00', '2008-11-29 00:00:00', '2014-02-24 00:00:00',
 '2010-05-14 00:00:00', '2010-01-07 00:00:00', '2009-12-29 00:00:00',
 '2010-01-01 00:00:00',
 ...
 '2017-02-11 00:00:00', '2017-02-12 00:00:00', '2017-02-13 00:00:00',
 '2017-02-14 00:00:00', '2017-02-15 00:00:00', '2017-02-16 00:00:00',
 '2017-02-17 00:00:00', '2017-02-19 00:00:00', '2017-02-20 00:00:00',
 '2017-02-21 00:00:00']
Length: 2427, dtype: datetime64[ns]

### Cleaning UCR Category Values

In [94]:
firearm_data['ucr_category'].unique()

array(['Homicide', 'Burglary', 'Aggravated Assault', 'Theft Fr Veh',
       'Robbery', 'Theft Other', 'Narcotics', 'Wpns Law Violation',
       'Family Offenses', 'Simple Assault', 'Suicide', 'Intimidation',
       'Death Investigation', 'Stolen Property', 'All Other Offenses',
       'Shoplifting', 'Justifiable Homicide', 'Injured Person Report',
       'Fraud Impersonation', 'Accidental Shooting', 'Counterfeiting',
       'Narcotics Equip', 'Prostitution', 'Vandalism', 'Sodomy Force',
       'Forcible Fondling', 'Auto Theft', 'Kidnapping Only', 'Fraud',
       'Forcible Rape', 'Disorderly Conduct', 'Theft Fr Vend Machine',
       'Theft Mv Parts', 'Liquor Law Viol', nan, 'Fraud Credit Card/Atm',
       'Bribery', 'Negligent Homicide', 'Purse Snatch', 'Theft Fr Bldg',
       'Promoting Prostitution'], dtype=object)

In [95]:
firearm_data['ucr_category'] = firearm_data['ucr_category'].replace(' ', '_', regex = True)

In [96]:
firearm_data['ucr_category'].unique()

array(['Homicide', 'Burglary', 'Aggravated_Assault', 'Theft_Fr_Veh',
       'Robbery', 'Theft_Other', 'Narcotics', 'Wpns_Law_Violation',
       'Family_Offenses', 'Simple_Assault', 'Suicide', 'Intimidation',
       'Death_Investigation', 'Stolen_Property', 'All_Other_Offenses',
       'Shoplifting', 'Justifiable_Homicide', 'Injured_Person_Report',
       'Fraud_Impersonation', 'Accidental_Shooting', 'Counterfeiting',
       'Narcotics_Equip', 'Prostitution', 'Vandalism', 'Sodomy_Force',
       'Forcible_Fondling', 'Auto_Theft', 'Kidnapping_Only', 'Fraud',
       'Forcible_Rape', 'Disorderly_Conduct', 'Theft_Fr_Vend_Machine',
       'Theft_Mv_Parts', 'Liquor_Law_Viol', nan, 'Fraud_Credit_Card/Atm',
       'Bribery', 'Negligent_Homicide', 'Purse_Snatch', 'Theft_Fr_Bldg',
       'Promoting_Prostitution'], dtype=object)

In [97]:
firearm_data['address_geocode_type'].unique()

array([nan, 'BLOCK'], dtype=object)

### Cleaning Firearm Manufacturer Values

In [98]:
firearm_data['firearm_manufacturer'].unique()

array([nan, 'Marlin Firearms Co.', 'Jennings Firear', 'Parabellum', 'Fie',
       'Smith & Wesson', 'F.E.G. Hungary', 'Harrington & Ri',
       'Armory Gun Co.', '', 'Ruger', 'Rohm', 'Remington Arms',
       'Glock, Inc.', 'Hipoint', 'Unknown Manufac', 'Charter Arms Co',
       'Rg Industries', 'Jimenez Arms', 'Lorcin Engineer',
       'New England Fir', 'Taurus Internat', 'Iver Johnson', 'Bryco Arms',
       'Keltec, Cnc Ind', 'Heckler & Koch', 'Raven Arms',
       'Connecticut Arm', 'Western Valley', 'O. F. Mossberg', 'Interamrs',
       'Cobra Enterpris', 'Sig-Sauer', 'Springfield Arm',
       'Bauer Fireamrs', 'Revelation', 'Mauser', 'North American',
       'Llama (Gabilond', 'Astar', 'Armscor', 'A Uberti',
       'Criterion Die A', 'Savage Arms Inc', 'Rg', 'Jc Higgins',
       'Davis Industrie', 'Valor', 'Harrington & Rn', 'Manurin S.A.',
       'Omega Arms Inc.', 'Arcadia Machine', 'Ft', 'Interarms',
       'High (Hi) Stand', 'Rossi - Amadeo', 'Beretta (P. Or',
       'Crossman Arms C', 'Omega Defensive', 'Thompson Center',
       'Stevens/J. Stev', 'Century Arms In', 'Titan Mfg. Corp', 'Colt',
       'High Standard M', 'Fmj (Full Metal', 'Springfield Fir', 'Bersa',
       'Century Mfg Inc', 'Marlin Firearms', 'Just, Joset',
       'Keltec, Cnc Industries, Inc', 'Lorcin', 'Skyy Industries',
       'Femaru', 'Kahr Arms', 'Keltec', 'Fabrinor Leguto', 'Winchester',
       'Mossberg', 'Phoenix Arms Co', 'Mossburg', 'Wesson Arms, Da',
       'Vzor', 'Alpha Arms', 'Turkey', 'Para Ordnance', 'Page 2',
       'Feather Ind Inc', 'Browning Arms C', 'Beretta (Indust',
       'Charter Arms', 'Sten', 'Waffenfabrik Wa', 'Astra Unceta Y',
       'Tisas', 'Wichester', 'Cobra', 'Quality Firearm', 'Cml (Chl?)',
       'Kbi Inc', 'Daewoo', 'Roth-Gasser', 'Sundance Ind In', 'Stoeger',
       'Heritage Mfg In', 'Manurhin', 'Taurus', 'Wyoming Arms',
       'Armalite', 'Rossi', 'Fnh Usa, Llc', 'Stallard Arms', 'Intratec',
       'Romarm/Cugir', 'Norinco', 'Hatsan Arms Co', 'Allen (Hopkins',
       'Radom', 'American Arms &', 'Titan', 'S.W.D. Industri',
       'Daisy Rifle Co', 'Nighthawk Custo', 'C  Harter Arms',
       'Bersa S.A.', 'Rexio, S.R.L.', 'Sr', 'Bryco', 'Iberia Firearms',
       'Ranger', 'Jimenez', 'Glock', 'Bond Arms Inc', 'Kahr', 'Sig Sauer',
       'Norinco (North', 'Arsenal Inc.', 'Lanber Armas', 'Lefever',
       'Rock Island Arm', 'D C Industries', 'Ind.Nac.De Arms', 'Bruni',
       'J C Higgins', 'Morrisburg', 'Saiga', 'Sterling Arms', 'Sportarms',
       'Omega Arms (All', 'Double Star Cor', 'Knight Rifle (M',
       'Weihrauch, Herm', 'Sportsman', 'Charles Daly', 'Star',
       'Rhoem Gesellsch', 'Izhmash (Imez)', 'Firearms Intern',
       'L. Romano Arms', 'Johnson Arms', 'Daniel Defense', 'Tradtions',
       'Tanfoglio, F.Ll', 'Kimber', 'Tru-Test', 'Magnum Research',
       'Gendarmaeria', 'Tisas Trabzon S', 'Champion Firear',
       'Armscor Of The', 'Davis Industris', 'Boito/Er Amanti', 'Crescent',
       'Masterpiece Arm', 'Gabilondo Y Cia', 'Armsco', 'Excam',
       'Iver Johnson Ar', 'Shaanki', 'American Arms', 'Raven', 'Liberty',
       'Eagle Arms', 'Unique', 'Buffalo Arms Co', 'Brescia Armas',
       'American Tacti', 'Armi Tanfoglioe', 'Butler Associat',
       'Ted Williams', 'Mass Arms', 'Kbi', 'Makarov', 'Bry',
       'Rock River Arms', 'Dpms Inc (Defen', 'F.E.G.', 'Connecticut Val',
       'Springfield Ary', 'Fabrique D Arme', 'Firestorm',
       'Derringer Corp.', 'Arms Co', 'Kurz', 'Israel Weapon I',
       'Barrett Firearm', 'European Americ', 'Clerke/Clerke T', 'Russian',
       'Traditions, Inc', 'Ithaca/Ithacagu', 'Essex Arms Comp',
       'Sterling', 'Western Field (', 'Beretta Usa Co', 'Cobray',
       'F&L Srl', 'Maadi Co', 'Bushmaster Fire', 'Longines',
       'Manufacture D`A', 'Feg', 'Janssen Sons &', 'Bowser',
       'Forehand Arms C', 'Del-Ton', 'Draco-C', 'American Classc',
       'France', 'Walther', 'Llama', 'Republic Arms,', 'Kel Tec',
       'Tanfoglio Giuse', 'Talon Industrie', 'Arsenal', 'Infallible',
       'Long Tom', 'Vector Arms, In', 'Marlin', 'Jpsauer&Sohn', 'Azul',
       'Us Revolver', 'Diamondback', 'Davis Indust', 'Lasserre S.A.',
       'Carl Walther', 'Phoenix Arms', 'American Fronti', 'Hm3',
       'Vanguard', 'Shinn-A-Sipja', 'Frontier', 'Miroku Fireamr',
       'Hopkins & Allen', 'Navy Arms Co', 'Arcus Co.', 'Eig',
       'Cz - Ceska Zbro', 'Westerfeld', 'Master Mag', 'Omega', 'Accu-Tek',
       'Old Saybrook', 'Sccy', 'Burgo', 'Dan Wesson Arms',
       'Taurus International', 'Nambu', 'S. S. Kresge', 'Maverick',
       'Aa Arms Corp.Mo', 'Calwestco Inc', 'Remington Arms Co., Inc.',
       'Revolution', 'Benelli', 'Springfield Armory,Geneseo,Il',
       'Harrington & Richardson', 'Charter Arms Corp.',
       'Waffenfabrik Walter', 'Cobra Enterprises Inc', 'Phoenix Arms Co.',
       'Skyy Industries, Llc', 'Davis Industries', 'Essex Arms Company',
       'Beretta (Industria S.A.)', 'Titan Mfg. Corp.',
       'Browning Arms Co.', 'Llama (Gabilondo & Cia)',
       'Tanfoglio Giuseppe', 'Heritage Mfg Inc', 'Forehand & Wads',
       'Rock River Arms, Inc.', 'New England Firearms', 'Schmidt-Rubin',
       'Rossi - Amadeo Rossi & Co', 'Cz (Short For Ceska Zbrojovka)',
       'Norinco (North China Industries)', 'European American Arms Corp.',
       'O. F. Mossberg & Sons', 'Grendel Inc.', 'Jennings Firearms',
       'Omega Defensive Industries', 'Charter 2000',
       'Unknown Manufacturer',
       'Firearms International Corp (Washington Dc)',
       'Beretta (P. Or Pietro)', 'Industria National De Armes', 'Haskell',
       'Merwin & Hubert (M & H)', 'Federal Engineering Corp',
       'Amtec 2000, Inc.', 'Clerke/Clerke Technicorp.',
       'Masterpiece Arms', 'Stevens/J. Stevens Arms Co.',
       'Thompson Center Arms Co.', 'Maltby & Henley', 'Erma/Erma Werke',
       'Hege Waffen', 'Dpms Inc (Defense Procurement Mfg Services)',
       'Glock Gmbh', 'North American Arms', 'Omega Arms (Allendale,Mi)',
       'Henry Repeating', 'Maverick Arms (Eagle Pass, Tx)',
       'Garate Anitua', 'F. M. M. A. P./Fammap',
       'Armscor Of The Philippines   Squires Bingham', 'Wesson Arms, Dan',
       'Hopkins & Allen (H & A)', 'Western Field (Montgomery Ward)',
       'Field & Fireside', 'Sport Arm Of Florida', 'Sedco Industrie',
       'New England Arms Co.', 'Double Star Corp', 'Hungary',
       'Nodak Spud Llc', 'Connecticut Valley Arms',
       'Tanfoglio, F.Lli, S.N.C', 'Maadi Company',
       'Tisas Trabzon Silah Sanayi', 'Waffenfabrik-Stenda Werke',
       'Astra Unceta Y Cia', 'Vulcan Arms Inc.', 'Arisaka',
       'High Standard Manufacturing Company (Houston)',
       'Iver Johnson Arms Inc., Hardwick, Vt', 'Excel Industries Inc',
       'Sauer & Sohn (S', 'High (Hi) Standard', 'Ranger Arms, Inc.',
       'Bauer Fireamrs Corp', 'German Sports Guns', 'Standard Arms Co.',
       'Century Arms International', 'Ithaca Guns Usa, Llc',
       'Talon Industries, Inc', 'Zastava', 'Pac West Arms',
       'Smith &Wesson', 'Hs Products (Im Metal)',
       'Indep/Fmp (Industrias Nacionas De Defensa Ep)',
       'Magnum Research Inc', 'Bushmaster Firearms',
       'Imperial Metal Products (Inca Manufacturing)', 'Armi E&F',
       'Metro Arms Corporation', 'Rigarmi/Rigarms',
       'American Tactical Imports (Ati)', 'Auto Ordnance', 'Precision',
       'Czechoslovakia', 'Liberty Arms Works',
       'Tikka - (Oy Tikkakoski Ab)', 'Cz - Ceska Zbrojovka',
       'Knight Rifle (Modern Muzzleloading)', 'Imbel', 'Laseraim Arms I',
       'Standard Arms O', 'Breda', 'Armi Effebi (Franco Beretta)',
       'Hawk Industries Inc', 'Armi Tecniche De Emilio Rizzini',
       'Anschutz', 'North America Arms Corp. (Toronto,Canada)', 'Sako',
       'Forehand Arms Co.', 'Fabrique D Armes De Guerre Precision',
       'Springfield Firearms Corporation', 'Sentinel Arms (Ridgeway, Pa)',
       'Ithaca/Ithacagun', 'Fabrinor', 'Argentina', 'Gustav, Carl',
       'Henry Repeating Rifle Co', 'Universal Firearms Corp.',
       'Sarsilmaz', 'Colt Sauer', 'Deutsche Treff', 'Polytechnologies',
       'Kessler Arms Corp.', 'Rock Island Armory Inc. (Geneseo, Il)',
       'Springfield (Military Rifles)', 'Arsenal Co. Bul', 'Msa',
       'Aa Arms Corp.Model Hill, Nc', 'Diamond Arms Co', 'Benelli S.P.A.',
       'Sundance Ind Inc N Hollywood, Ca', 'American Firear', 'Canada',
       'Connecticut Arms & Mfg. Co.', 'Metro Arms Corp', 'Sarmco',
       'Bohnmische Waffenfabrik', 'Webley - Webley', 'Cobolt',
       'J. P. Sauer & Sons', 'Girsan',
       'Lucznik, Fabryka Broni (Z M Lucznik)', 'Marksman Products Inc',
       'Maverick Arms (', 'Massachusetts Arms Co', 'Enterprise Arms',
       'Fabrica De Bera', 'Phoenix', 'Armi Atis S. R. L.',
       'Israel Weapon Ind - Iwi (Israel Military Inc - Imi)',
       'Romer/Romerwerk', 'Criterion Die And Metal Inc',
       'Hwp Enterprises', 'Jukar', 'Armero Especial',
       'Arcadia Machine & Tool', 'B. H.', 'Weihrauch, Hermann',
       'Olympic Arms Inc', 'Enfield', 'Stag Arms', 'Issc Austria',
       'Diamond Arms Co.', 'Cimarron Arms',
       'Union Arms Co. (Union Firearms Co.)', 'Romania',
       'Brevettate Industria Armi', 'German Sports G',
       'Meriden Firearms Co', 'Anderson Manufa', 'Serrifile Inc',
       'Leinad Inc', 'Liberty Arms Wo',
       'Cbc (Cia Brazileria De Cartuchos)', 'Scorpion', 'American Tactic',
       'American Derringer Co', 'D Max Industrie', 'Fratelli Bertuzzi',
       'Sardius Industries, Ltd', 'Worcester, Ma', 'Marksman Produc',
       'Haenel-Schmeisser', 'Coharie Arms', 'Miroku Fireamr Co',
       'Spike S Tactical Llc', 'Falcon', 'Iraola Salaverr',
       'Garate, Anitua Y Cia', 'Canik', 'Mf (Manufrance)',
       'Caspian Arms Lt', 'Vulcain', 'Volunteer Enterprises Inc.',
       'I O Inc (Inter Ordinance)', 'Herters', 'Comanche Fireamrs',
       'Sedco Industries', 'Fmj (Full Metal Jacket)', 'Echasa',
       'Kodiak Mfg. Co.', 'Remington Arms Union', 'Chinese',
       'Smith And Wesson', 'Waffen Franconi', 'Steyr', 'Ram Line, Inc.',
       'Uniwerke', 'Shooters Depot', 'Industria Natio', 'Khan Shotguns',
       'Arsenal Co. Bulgaria', 'Baikal', 'Anderson Manufacturing',
       'Sauer & Sohn (S & S)', 'Beistegui', 'Zhong Zhou Machine Works',
       'Sig', 'Crossman Arms Co', 'Beeman', 'Keystone Sporti',
       'Britarms Of England', 'Firearms International Inc (Houston, Tx)',
       'Fulton Armory', 'Cmmg Inc', 'Universal Firea',
       'Akkar Silah Sanayi Tic. Ltd.',
       'Armscorp Usa (Armscorp Of America)', 'Federal Ordinance',
       'Hamilton', 'Shinkosha', 'Revelli', 'Western Arms Corp.',
       'Fabrica De Armas Mexico City', 'Raptor Arms Co., Inc.',
       'Itm Arms Company', 'Ruby Arms Co.', 'Pietro Zanoletti',
       'Standard Arms Of Nevada'], dtype=object)

In [99]:
firearm_data['firearm_manufacturer'] = firearm_data['firearm_manufacturer'].replace(' ', '_', regex = True)
firearm_data['firearm_manufacturer'] = firearm_data['firearm_manufacturer'].replace('', np.NaN)
firearm_data['firearm_manufacturer'] = firearm_data['firearm_manufacturer'].replace('Unk', np.NaN)
firearm_data['firearm_manufacturer'] = firearm_data['firearm_manufacturer'].replace('Unknown', np.NaN)
firearm_data['firearm_manufacturer'] = firearm_data['firearm_manufacturer'].replace(' ', np.NaN)

In [100]:
firearm_data['firearm_manufacturer'].unique()

array([nan, 'Marlin_Firearms_Co.', 'Jennings_Firear', 'Parabellum', 'Fie',
       'Smith_&_Wesson', 'F.E.G._Hungary', 'Harrington_&_Ri',
       'Armory_Gun_Co.', 'Ruger', 'Rohm', 'Remington_Arms', 'Glock,_Inc.',
       'Hipoint', 'Unknown_Manufac', 'Charter_Arms_Co', 'Rg_Industries',
       'Jimenez_Arms', 'Lorcin_Engineer', 'New_England_Fir',
       'Taurus_Internat', 'Iver_Johnson', 'Bryco_Arms', 'Keltec,_Cnc_Ind',
       'Heckler_&_Koch', 'Raven_Arms', 'Connecticut_Arm',
       'Western_Valley', 'O._F._Mossberg', 'Interamrs', 'Cobra_Enterpris',
       'Sig-Sauer', 'Springfield_Arm', 'Bauer_Fireamrs', 'Revelation',
       'Mauser', 'North_American', 'Llama_(Gabilond', 'Astar', 'Armscor',
       'A_Uberti', 'Criterion_Die_A', 'Savage_Arms_Inc', 'Rg',
       'Jc_Higgins', 'Davis_Industrie', 'Valor', 'Harrington_&_Rn',
       'Manurin_S.A.', 'Omega_Arms_Inc.', 'Arcadia_Machine', 'Ft',
       'Interarms', 'High_(Hi)_Stand', 'Rossi_-_Amadeo', 'Beretta_(P._Or',
       'Crossman_Arms_C', 'Omega_Defensive', 'Thompson_Center',
       'Stevens/J._Stev', 'Century_Arms_In', 'Titan_Mfg._Corp', 'Colt',
       'High_Standard_M', 'Fmj_(Full_Metal', 'Springfield_Fir', 'Bersa',
       'Century_Mfg_Inc', 'Marlin_Firearms', 'Just,_Joset',
       'Keltec,_Cnc_Industries,_Inc', 'Lorcin', 'Skyy_Industries',
       'Femaru', 'Kahr_Arms', 'Keltec', 'Fabrinor_Leguto', 'Winchester',
       'Mossberg', 'Phoenix_Arms_Co', 'Mossburg', 'Wesson_Arms,_Da',
       'Vzor', 'Alpha_Arms', 'Turkey', 'Para_Ordnance', 'Page_2',
       'Feather_Ind_Inc', 'Browning_Arms_C', 'Beretta_(Indust',
       'Charter_Arms', 'Sten', 'Waffenfabrik_Wa', 'Astra_Unceta_Y',
       'Tisas', 'Wichester', 'Cobra', 'Quality_Firearm', 'Cml_(Chl?)',
       'Kbi_Inc', 'Daewoo', 'Roth-Gasser', 'Sundance_Ind_In', 'Stoeger',
       'Heritage_Mfg_In', 'Manurhin', 'Taurus', 'Wyoming_Arms',
       'Armalite', 'Rossi', 'Fnh_Usa,_Llc', 'Stallard_Arms', 'Intratec',
       'Romarm/Cugir', 'Norinco', 'Hatsan_Arms_Co', 'Allen_(Hopkins',
       'Radom', 'American_Arms_&', 'Titan', 'S.W.D._Industri',
       'Daisy_Rifle_Co', 'Nighthawk_Custo', 'C__Harter_Arms',
       'Bersa_S.A.', 'Rexio,_S.R.L.', 'Sr', 'Bryco', 'Iberia_Firearms',
       'Ranger', 'Jimenez', 'Glock', 'Bond_Arms_Inc', 'Kahr', 'Sig_Sauer',
       'Norinco_(North', 'Arsenal_Inc.', 'Lanber_Armas', 'Lefever',
       'Rock_Island_Arm', 'D_C_Industries', 'Ind.Nac.De_Arms', 'Bruni',
       'J_C_Higgins', 'Morrisburg', 'Saiga', 'Sterling_Arms', 'Sportarms',
       'Omega_Arms_(All', 'Double_Star_Cor', 'Knight_Rifle_(M',
       'Weihrauch,_Herm', 'Sportsman', 'Charles_Daly', 'Star',
       'Rhoem_Gesellsch', 'Izhmash_(Imez)', 'Firearms_Intern',
       'L._Romano_Arms', 'Johnson_Arms', 'Daniel_Defense', 'Tradtions',
       'Tanfoglio,_F.Ll', 'Kimber', 'Tru-Test', 'Magnum_Research',
       'Gendarmaeria', 'Tisas_Trabzon_S', 'Champion_Firear',
       'Armscor_Of_The', 'Davis_Industris', 'Boito/Er_Amanti', 'Crescent',
       'Masterpiece_Arm', 'Gabilondo_Y_Cia', 'Armsco', 'Excam',
       'Iver_Johnson_Ar', 'Shaanki', 'American_Arms', 'Raven', 'Liberty',
       'Eagle_Arms', 'Unique', 'Buffalo_Arms_Co', 'Brescia_Armas',
       'American_Tacti', 'Armi_Tanfoglioe', 'Butler_Associat',
       'Ted_Williams', 'Mass_Arms', 'Kbi', 'Makarov', 'Bry',
       'Rock_River_Arms', 'Dpms_Inc_(Defen', 'F.E.G.', 'Connecticut_Val',
       'Springfield_Ary', 'Fabrique_D_Arme', 'Firestorm',
       'Derringer_Corp.', 'Arms_Co', 'Kurz', 'Israel_Weapon_I',
       'Barrett_Firearm', 'European_Americ', 'Clerke/Clerke_T', 'Russian',
       'Traditions,_Inc', 'Ithaca/Ithacagu', 'Essex_Arms_Comp',
       'Sterling', 'Western_Field_(', 'Beretta_Usa_Co', 'Cobray',
       'F&L_Srl', 'Maadi_Co', 'Bushmaster_Fire', 'Longines',
       'Manufacture_D`A', 'Feg', 'Janssen_Sons_&', 'Bowser',
       'Forehand_Arms_C', 'Del-Ton', 'Draco-C', 'American_Classc',
       'France', 'Walther', 'Llama', 'Republic_Arms,', 'Kel_Tec',
       'Tanfoglio_Giuse', 'Talon_Industrie', 'Arsenal', 'Infallible',
       'Long_Tom', 'Vector_Arms,_In', 'Marlin', 'Jpsauer&Sohn', 'Azul',
       'Us_Revolver', 'Diamondback', 'Davis_Indust', 'Lasserre_S.A.',
       'Carl_Walther', 'Phoenix_Arms', 'American_Fronti', 'Hm3',
       'Vanguard', 'Shinn-A-Sipja', 'Frontier', 'Miroku_Fireamr',
       'Hopkins_&_Allen', 'Navy_Arms_Co', 'Arcus_Co.', 'Eig',
       'Cz_-_Ceska_Zbro', 'Westerfeld', 'Master_Mag', 'Omega', 'Accu-Tek',
       'Old_Saybrook', 'Sccy', 'Burgo', 'Dan_Wesson_Arms',
       'Taurus_International', 'Nambu', 'S._S._Kresge', 'Maverick',
       'Aa_Arms_Corp.Mo', 'Calwestco_Inc', 'Remington_Arms_Co.,_Inc.',
       'Revolution', 'Benelli', 'Springfield_Armory,Geneseo,Il',
       'Harrington_&_Richardson', 'Charter_Arms_Corp.',
       'Waffenfabrik_Walter', 'Cobra_Enterprises_Inc', 'Phoenix_Arms_Co.',
       'Skyy_Industries,_Llc', 'Davis_Industries', 'Essex_Arms_Company',
       'Beretta_(Industria_S.A.)', 'Titan_Mfg._Corp.',
       'Browning_Arms_Co.', 'Llama_(Gabilondo_&_Cia)',
       'Tanfoglio_Giuseppe', 'Heritage_Mfg_Inc', 'Forehand_&_Wads',
       'Rock_River_Arms,_Inc.', 'New_England_Firearms', 'Schmidt-Rubin',
       'Rossi_-_Amadeo_Rossi_&_Co', 'Cz_(Short_For_Ceska_Zbrojovka)',
       'Norinco_(North_China_Industries)', 'European_American_Arms_Corp.',
       'O._F._Mossberg_&_Sons', 'Grendel_Inc.', 'Jennings_Firearms',
       'Omega_Defensive_Industries', 'Charter_2000',
       'Unknown_Manufacturer',
       'Firearms_International_Corp_(Washington_Dc)',
       'Beretta_(P._Or_Pietro)', 'Industria_National_De_Armes', 'Haskell',
       'Merwin_&_Hubert_(M_&_H)', 'Federal_Engineering_Corp',
       'Amtec_2000,_Inc.', 'Clerke/Clerke_Technicorp.',
       'Masterpiece_Arms', 'Stevens/J._Stevens_Arms_Co.',
       'Thompson_Center_Arms_Co.', 'Maltby_&_Henley', 'Erma/Erma_Werke',
       'Hege_Waffen', 'Dpms_Inc_(Defense_Procurement_Mfg_Services)',
       'Glock_Gmbh', 'North_American_Arms', 'Omega_Arms_(Allendale,Mi)',
       'Henry_Repeating', 'Maverick_Arms_(Eagle_Pass,_Tx)',
       'Garate_Anitua', 'F._M._M._A._P./Fammap',
       'Armscor_Of_The_Philippines___Squires_Bingham', 'Wesson_Arms,_Dan',
       'Hopkins_&_Allen_(H_&_A)', 'Western_Field_(Montgomery_Ward)',
       'Field_&_Fireside', 'Sport_Arm_Of_Florida', 'Sedco_Industrie',
       'New_England_Arms_Co.', 'Double_Star_Corp', 'Hungary',
       'Nodak_Spud_Llc', 'Connecticut_Valley_Arms',
       'Tanfoglio,_F.Lli,_S.N.C', 'Maadi_Company',
       'Tisas_Trabzon_Silah_Sanayi', 'Waffenfabrik-Stenda_Werke',
       'Astra_Unceta_Y_Cia', 'Vulcan_Arms_Inc.', 'Arisaka',
       'High_Standard_Manufacturing_Company_(Houston)',
       'Iver_Johnson_Arms_Inc.,_Hardwick,_Vt', 'Excel_Industries_Inc',
       'Sauer_&_Sohn_(S', 'High_(Hi)_Standard', 'Ranger_Arms,_Inc.',
       'Bauer_Fireamrs_Corp', 'German_Sports_Guns', 'Standard_Arms_Co.',
       'Century_Arms_International', 'Ithaca_Guns_Usa,_Llc',
       'Talon_Industries,_Inc', 'Zastava', 'Pac_West_Arms',
       'Smith_&Wesson', 'Hs_Products_(Im_Metal)',
       'Indep/Fmp_(Industrias_Nacionas_De_Defensa_Ep)',
       'Magnum_Research_Inc', 'Bushmaster_Firearms',
       'Imperial_Metal_Products_(Inca_Manufacturing)', 'Armi_E&F',
       'Metro_Arms_Corporation', 'Rigarmi/Rigarms',
       'American_Tactical_Imports_(Ati)', 'Auto_Ordnance', 'Precision',
       'Czechoslovakia', 'Liberty_Arms_Works',
       'Tikka_-_(Oy_Tikkakoski_Ab)', 'Cz_-_Ceska_Zbrojovka',
       'Knight_Rifle_(Modern_Muzzleloading)', 'Imbel', 'Laseraim_Arms_I',
       'Standard_Arms_O', 'Breda', 'Armi_Effebi_(Franco_Beretta)',
       'Hawk_Industries_Inc', 'Armi_Tecniche_De_Emilio_Rizzini',
       'Anschutz', 'North_America_Arms_Corp._(Toronto,Canada)', 'Sako',
       'Forehand_Arms_Co.', 'Fabrique_D_Armes_De_Guerre_Precision',
       'Springfield_Firearms_Corporation', 'Sentinel_Arms_(Ridgeway,_Pa)',
       'Ithaca/Ithacagun', 'Fabrinor', 'Argentina', 'Gustav,_Carl',
       'Henry_Repeating_Rifle_Co', 'Universal_Firearms_Corp.',
       'Sarsilmaz', 'Colt_Sauer', 'Deutsche_Treff', 'Polytechnologies',
       'Kessler_Arms_Corp.', 'Rock_Island_Armory_Inc._(Geneseo,_Il)',
       'Springfield_(Military_Rifles)', 'Arsenal_Co._Bul', 'Msa',
       'Aa_Arms_Corp.Model_Hill,_Nc', 'Diamond_Arms_Co', 'Benelli_S.P.A.',
       'Sundance_Ind_Inc_N_Hollywood,_Ca', 'American_Firear', 'Canada',
       'Connecticut_Arms_&_Mfg._Co.', 'Metro_Arms_Corp', 'Sarmco',
       'Bohnmische_Waffenfabrik', 'Webley_-_Webley', 'Cobolt',
       'J._P._Sauer_&_Sons', 'Girsan',
       'Lucznik,_Fabryka_Broni_(Z_M_Lucznik)', 'Marksman_Products_Inc',
       'Maverick_Arms_(', 'Massachusetts_Arms_Co', 'Enterprise_Arms',
       'Fabrica_De_Bera', 'Phoenix', 'Armi_Atis_S._R._L.',
       'Israel_Weapon_Ind_-_Iwi_(Israel_Military_Inc_-_Imi)',
       'Romer/Romerwerk', 'Criterion_Die_And_Metal_Inc',
       'Hwp_Enterprises', 'Jukar', 'Armero_Especial',
       'Arcadia_Machine_&_Tool', 'B._H.', 'Weihrauch,_Hermann',
       'Olympic_Arms_Inc', 'Enfield', 'Stag_Arms', 'Issc_Austria',
       'Diamond_Arms_Co.', 'Cimarron_Arms',
       'Union_Arms_Co._(Union_Firearms_Co.)', 'Romania',
       'Brevettate_Industria_Armi', 'German_Sports_G',
       'Meriden_Firearms_Co', 'Anderson_Manufa', 'Serrifile_Inc',
       'Leinad_Inc', 'Liberty_Arms_Wo',
       'Cbc_(Cia_Brazileria_De_Cartuchos)', 'Scorpion', 'American_Tactic',
       'American_Derringer_Co', 'D_Max_Industrie', 'Fratelli_Bertuzzi',
       'Sardius_Industries,_Ltd', 'Worcester,_Ma', 'Marksman_Produc',
       'Haenel-Schmeisser', 'Coharie_Arms', 'Miroku_Fireamr_Co',
       'Spike_S_Tactical_Llc', 'Falcon', 'Iraola_Salaverr',
       'Garate,_Anitua_Y_Cia', 'Canik', 'Mf_(Manufrance)',
       'Caspian_Arms_Lt', 'Vulcain', 'Volunteer_Enterprises_Inc.',
       'I_O_Inc_(Inter_Ordinance)', 'Herters', 'Comanche_Fireamrs',
       'Sedco_Industries', 'Fmj_(Full_Metal_Jacket)', 'Echasa',
       'Kodiak_Mfg._Co.', 'Remington_Arms_Union', 'Chinese',
       'Smith_And_Wesson', 'Waffen_Franconi', 'Steyr', 'Ram_Line,_Inc.',
       'Uniwerke', 'Shooters_Depot', 'Industria_Natio', 'Khan_Shotguns',
       'Arsenal_Co._Bulgaria', 'Baikal', 'Anderson_Manufacturing',
       'Sauer_&_Sohn_(S_&_S)', 'Beistegui', 'Zhong_Zhou_Machine_Works',
       'Sig', 'Crossman_Arms_Co', 'Beeman', 'Keystone_Sporti',
       'Britarms_Of_England', 'Firearms_International_Inc_(Houston,_Tx)',
       'Fulton_Armory', 'Cmmg_Inc', 'Universal_Firea',
       'Akkar_Silah_Sanayi_Tic._Ltd.',
       'Armscorp_Usa_(Armscorp_Of_America)', 'Federal_Ordinance',
       'Hamilton', 'Shinkosha', 'Revelli', 'Western_Arms_Corp.',
       'Fabrica_De_Armas_Mexico_City', 'Raptor_Arms_Co.,_Inc.',
       'Itm_Arms_Company', 'Ruby_Arms_Co.', 'Pietro_Zanoletti',
       'Standard_Arms_Of_Nevada'], dtype=object)

### Cleaning Firearm Model Values

In [101]:
firearm_data['firearm_model'].unique()

array([nan, 'Modle 25 Series', 'Jennings Firear', ..., 'Double Nine',
       'H&R Model 732', 'Cal 22 Lr Hv'], dtype=object)

In [102]:
firearm_data['firearm_model'] = firearm_data['firearm_model'].replace(' ', '_', regex = True)
firearm_data['firearm_model'] = firearm_data['firearm_model'].replace('', np.NaN)
firearm_data['firearm_model'] = firearm_data['firearm_model'].replace(' ', np.NaN)

In [103]:
firearm_data['firearm_model'].unique()

array([nan, 'Modle_25_Series', 'Jennings_Firear', ..., 'Double_Nine',
       'H&R_Model_732', 'Cal_22_Lr_Hv'], dtype=object)

### Cleaning Firearm Subcategory Values

In [104]:
firearm_data['firearm_subcategory'].unique()

array([nan, 'Single-Shot', 'Semi-Automatic', 'Revolver', 'Pump Action',
       'Automatic', 'Semi-automatic', 'Bolt Action', 'Percussion',
       'Derringer', 'Flintlock', 'Lever Action', 'Carbine', 'Single-shot',
       'Double Barrel', 'Semiautomatic', 'Jet Propelled',
       'Over And Under'], dtype=object)

In [105]:
firearm_data['firearm_subcategory'] = firearm_data['firearm_subcategory'].replace('Semi-automatic', 'Semi-Automatic')
firearm_data['firearm_subcategory'] = firearm_data['firearm_subcategory'].replace('Semiautomatic', 'Semi-Automatic')
firearm_data['firearm_subcategory'] = firearm_data['firearm_subcategory'].replace('Single-shot', 'Single-Shot')
firearm_data['firearm_subcategory'] = firearm_data['firearm_subcategory'].replace(' ', '_', regex = True)

In [106]:
firearm_data['firearm_subcategory'].unique()

array([nan, 'Single-Shot', 'Semi-Automatic', 'Revolver', 'Pump_Action',
       'Automatic', 'Bolt_Action', 'Percussion', 'Derringer', 'Flintlock',
       'Lever_Action', 'Carbine', 'Double_Barrel', 'Jet_Propelled',
       'Over_And_Under'], dtype=object)

### Cleaning Firearm Category Values

In [107]:
firearm_data['firearm_category'].unique()

array([nan, 'Rifle', 'Pistol', 'Shotgun', 'Airgun',
       'Electronic Control Weapon', 'Submachine Gun (Machine Pistol)',
       'Machine Gun', 'Rifle-Shotgun Combination',
       'Submachine Gun (machine Pistol)'], dtype=object)

In [108]:
firearm_data['firearm_category'] = firearm_data['firearm_category'].replace('Submachine Gun (machine Pistol)', 'Submachine Gun')
firearm_data['firearm_category'] = firearm_data['firearm_category'].replace('Submachine Gun (Machine Pistol)', 'Submachine Gun')
firearm_data['firearm_category'] = firearm_data['firearm_category'].replace(' ', '_', regex = True)

In [109]:
firearm_data['firearm_category'].unique()

array([nan, 'Rifle', 'Pistol', 'Shotgun', 'Airgun',
       'Electronic_Control_Weapon', 'Submachine_Gun', 'Machine_Gun',
       'Rifle-Shotgun_Combination'], dtype=object)

### Cleaning Firearm Caliber Values

In [110]:
firearm_data['firearm_caliber'].unique()

array([nan, '', '380C', '9MM', '25C', '38C', '6666', '357C', '12GA',
       '22C', '40C', '45C', '222C', '4570', '32C', '50C', '3006', '763M',
       '44C', '735M', '765M', '20GA', '177C', '762M', '410G', '36C',
       '223C', '30C', '10MM', '556M', '57', '16GA', '35C', '243C', '3220',
       '308C', '8MM', '375C', '270C', '41C', '7MM', '455C', '75MM', '17C',
       '635M', '300C', '58C', '10GA', '257C', '338C', '6MM', '28GA',
       '401C', '54C', '221C', '250C', '444C', '204', '24GA', '32GA',
       '303C'], dtype=object)

In [111]:
firearm_data['firearm_caliber'] = firearm_data['firearm_caliber'].replace('', np.NaN)

In [112]:
firearm_data['firearm_caliber'].unique()

array([nan, '380C', '9MM', '25C', '38C', '6666', '357C', '12GA', '22C',
       '40C', '45C', '222C', '4570', '32C', '50C', '3006', '763M', '44C',
       '735M', '765M', '20GA', '177C', '762M', '410G', '36C', '223C',
       '30C', '10MM', '556M', '57', '16GA', '35C', '243C', '3220', '308C',
       '8MM', '375C', '270C', '41C', '7MM', '455C', '75MM', '17C', '635M',
       '300C', '58C', '10GA', '257C', '338C', '6MM', '28GA', '401C',
       '54C', '221C', '250C', '444C', '204', '24GA', '32GA', '303C'],
      dtype=object)

### Cleaning Street Address Values

In [113]:
len(list(firearm_data['street_address'].unique()))

2672

In [114]:
firearm_data['street_address'] = firearm_data['street_address'].replace('', np.NaN)
firearm_data['street_address'] = firearm_data['street_address'].replace('Unk', np.NaN)
firearm_data['street_address'] = firearm_data['street_address'].replace(' ', '_', regex = True)

In [115]:
len(list(firearm_data['street_address'].unique()))

2672

### Cleaning City Values

In [116]:
firearm_data['city'].unique()

array(['Louisville', 'Lyndon', 'Shively', 'Worthington_Hills', 'Lynnview',
       'Middletown', 'Mede', 'Douglass_Hills', 'Rolling_Hills',
       'St_Matthews', 'Shv', 'Lynd', 'Dhil', 'Watterson_Park',
       'Woodlawn_Park', 'Wb', 'Stm', 'Jeffersontown', '', 'Fincastle',
       'Brownsboro_Village', 'Glenview', 'Hurs', 'Mtwn', 'Pro', 'Rhil',
       'Ft Knox', 'Poplar_Hills', 'Strathmoor_Village', 'Windy_Hills',
       'Briarwood', 'West_Buechel', 'Norwood', 'Hickory_Hill', 'Unk',
       'Hollyvilla', 'Wtwd', 'Green_Spring', 'Druid_Hills', 'Moorland',
       'Hurstbourne_Acres', 'Prospect', 'Blue_Ridge_Manor', 'Hurstbourne',
       'Woodland_Hills', 'Houston_Acres', 'Graymoor/Devondale',
       'West Point', 'Murray_Hill', 'New Albany', 'Williamstown',
       'Jeffersonville', 'Audubon_Park', 'Mammoth Cave', 'Fairdale',
       'Plantation', 'Creekside', 'Shepherdsville', 'St_Regis_Park',
       'Forest_Hills', 'Htck'], dtype=object)

In [117]:
firearm_data['city'] = firearm_data['city'].replace('', np.NaN)
firearm_data['city'] = firearm_data['city'].replace('Unk', np.NaN)
firearm_data['city'] = firearm_data['city'].replace(' ', '_', regex = True)
firearm_city_unk = firearm_data.query("city=='Htck' or city=='Lynd' or city=='Wtwd' or city=='Mede' or city=='Hurs' or city=='Pro' or city=='Mtwn' or city=='Shv' or city=='Rhil' or city=='Stm' or city=='Wb'or city=='Dhil'")

In [118]:
firearm_city_unk.head()

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,street_address,city,state,zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
266,80-10-016017,2010,2010-03-06,Wpns_Law_Violation,Pistol,Revolver,Omega_Defensive,Mod_100,22C,NaN,...,NaN,Mede,KY,40220,NaN,NaN,Black,M,19.0,NaN
443,80-10-028727,2010,2010-04-21,Wpns_Law_Violation,Pistol,Semi-Automatic,Smith_&_Wesson,Pistols:_4046,40C,BLOCK,...,2900_7th_Street_Rd,Shv,KY,,-86.250692,43.199428,Black,M,37.0,0.500
542,80-10-032882,2010,2010-05-05,Wpns_Law_Violation,Pistol,Semi-Automatic,NaN,NaN,9MM,BLOCK,...,600_W._Jefferson_St,Shv,KY,40216,-85.761323,38.253961,Black,M,21.0,1.000
543,80-10-032882,2010,2010-05-05,Wpns_Law_Violation,Pistol,Semi-Automatic,NaN,NaN,9MM,BLOCK,...,3100_7th_Street_Rd,Shv,KY,40216,-85.798374,38.212287,Black,M,21.0,0.728
545,80-10-032882,2010,2010-05-05,Wpns_Law_Violation,Pistol,Revolver,Rohm,NaN,22C,BLOCK,...,600_W._Jefferson_St,Shv,KY,40216,-85.761323,38.253961,Black,M,21.0,1.000

In [119]:
unk_city_index = firearm_data.query("city=='Htck' or city=='Lynd' or city=='Wtwd' or city=='Mede' or city=='Hurs' or city=='Pro' or city=='Mtwn' or city=='Shv' or city=='Rhil' or city=='Stm' or city=='Wb'or city=='Dhil'").index
unk_city_index
firearm_data.drop(unk_city_index, inplace = True)

In [120]:
firearm_data['city'].unique()

array(['Louisville', 'Lyndon', 'Shively', 'Worthington_Hills', 'Lynnview',
       'Middletown', 'Douglass_Hills', 'Rolling_Hills', 'St_Matthews',
       'Watterson_Park', 'Woodlawn_Park', 'Jeffersontown', nan,
       'Fincastle', 'Brownsboro_Village', 'Glenview', 'Ft_Knox',
       'Poplar_Hills', 'Strathmoor_Village', 'Windy_Hills', 'Briarwood',
       'West_Buechel', 'Norwood', 'Hickory_Hill', 'Hollyvilla',
       'Green_Spring', 'Druid_Hills', 'Moorland', 'Hurstbourne_Acres',
       'Prospect', 'Blue_Ridge_Manor', 'Hurstbourne', 'Woodland_Hills',
       'Houston_Acres', 'Graymoor/Devondale', 'West_Point', 'Murray_Hill',
       'New_Albany', 'Williamstown', 'Jeffersonville', 'Audubon_Park',
       'Mammoth_Cave', 'Fairdale', 'Plantation', 'Creekside',
       'Shepherdsville', 'St_Regis_Park', 'Forest_Hills'], dtype=object)

### Cleaning State Values

In [121]:
firearm_data['state'].unique()

array(['KY', '', 'IN'], dtype=object)

In [122]:
firearm_data['state'] = firearm_data['state'].replace('', np.NaN)

In [123]:
firearm_data['state'].unique()

array(['KY', nan, 'IN'], dtype=object)

### Cleaning Zipcode Values

In [124]:
firearm_data['zipcode'].unique()

array(['40202', '40272', '40216', '40210', '40203', '40220', '40206',
       '40212', '40208', '40118', '40211', '40214', '40219', '40215',
       '40204', '40228', '40223', '40056', '40222', '40218', '40229',
       '40241', '40291', '40207', '40213', '', '40242', '40245', '40258',
       '40217', '40059', '40209', '40205', '40299', '40243', '40225',
       '40058', '40023', '40177', '42259', '47130', '40165'], dtype=object)

In [125]:
firearm_data['zipcode'] = firearm_data['zipcode'].replace('', np.NaN)

In [126]:
firearm_data['zipcode'].unique()

array(['40202', '40272', '40216', '40210', '40203', '40220', '40206',
       '40212', '40208', '40118', '40211', '40214', '40219', '40215',
       '40204', '40228', '40223', '40056', '40222', '40218', '40229',
       '40241', '40291', '40207', '40213', nan, '40242', '40245', '40258',
       '40217', '40059', '40209', '40205', '40299', '40243', '40225',
       '40058', '40023', '40177', '42259', '47130', '40165'], dtype=object)

### Cleaning Race Values

In [127]:
firearm_data['person_recovered_from_race'].unique()

array([nan, 'White', 'Black', 'Unknown', 'Hispanic', 'Asian',
       'American Indian', 'Middle Eastern', 'Indian/India/Burmese'],
      dtype=object)

In [128]:
firearm_data['person_recovered_from_race'] = firearm_data['person_recovered_from_race'].replace('Unknown', np.NaN)
firearm_data['person_recovered_from_race'] = firearm_data['person_recovered_from_race'].replace('Indian/India/Burmese', 'Indian/Burmese_Indian')
firearm_data['person_recovered_from_race'] = firearm_data['person_recovered_from_race'].replace('American Indian', 'Native American')
firearm_data['person_recovered_from_race'] = firearm_data['person_recovered_from_race'].replace(' ', '_', regex = True)

### Cleaning Sex Values

In [129]:
firearm_data['person_recovered_from_sex'].unique()

array([nan, 'M', 'F', 'U'], dtype=object)

In [130]:
firearm_data['person_recovered_from_sex'] = firearm_data['person_recovered_from_sex'].replace('U', np.NaN)

In [131]:
firearm_data['person_recovered_from_sex'].unique()

array([nan, 'M', 'F'], dtype=object)

### Cleaning Age Values

In [132]:
firearm_data['person_recovered_from_age'].unique()

array([nan, 38., 30., 25., 15., 45., 17., 56., 23., 32., 27., 22., 46.,
       28., 42., 18., 43., 47., 36., 35., 21., 41., 19., 39., 20., 66.,
       26., 16., 24., 55., 31., 40., 29., 53., 33., 44., 34., 59., 52.,
       50., 14., 57., 48., 64., 61.,  0., 37., 51., 12., 58., 68., 54.,
       65., 49., 60., 63., 13., 69., 62., 82., 70., 72., 11., 67.,  9.,
       75., 71., 83., 73., 77., 80., 87., 74., 85., 76.])

In [133]:
firearm_data = firearm_data.drop_duplicates()

In [134]:
firearm_data

,incident_number,year,recovery_date,ucr_category,firearm_category,firearm_subcategory,firearm_manufacturer,firearm_model,firearm_caliber,address_geocode_type,...,street_address,city,state,zipcode,longitude,latitude,person_recovered_from_race,person_recovered_from_sex,person_recovered_from_age,confidence
0,80-06-008380,NaN,NaT,Homicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40202,0.000000,0.000000,NaN,NaN,NaN,0.00
1,80-06-108219,2014,2014-07-30,Burglary,Rifle,Single-Shot,Marlin_Firearms_Co.,Modle_25_Series,NaN,BLOCK,...,4700_Haney_Way,Louisville,KY,40272,-85.850950,38.096623,White,M,38.0,1.00
2,80-08-008343,2010,2010-01-20,Burglary,Pistol,Semi-Automatic,Jennings_Firear,Jennings_Firear,380C,BLOCK,...,3400_Shagbark_Rd,Louisville,KY,40216,-85.843407,38.196532,Black,M,30.0,1.00
3,80-08-047627,2012,2012-06-18,Aggravated_Assault,Pistol,Semi-Automatic,Parabellum,NaN,9MM,BLOCK,...,1700_W_Hill_St,Louisville,KY,40210,-85.784928,38.227766,Black,M,25.0,1.00
4,80-08-091695,2008,2008-11-29,Theft_Fr_Veh,Pistol,Semi-Automatic,Fie,E28,25C,BLOCK,...,1000_Cladwell,Louisville,KY,40203,-85.757053,38.238555,White,M,15.0,0.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23656,80-17-014921,2017,2017-02-21,Wpns_Law_Violation,NaN,NaN,"Glock,_Inc.",Model_31/31C_(3,NaN,BLOCK,...,600_W_Jefferson_St,Louisville,KY,40202,-85.761323,38.253961,Black,M,24.0,1.00
23657,80-17-014942,2017,2017-02-21,Narcotics,Pistol,Semi-Automatic,Cobra_Enterprises_Inc,Ca_Series,380C,BLOCK,...,4200_S_2nd_St,Louisville,KY,40214,-85.763628,38.195203,Black,F,19.0,1.00
23658,80-17-015000,2017,2017-02-21,Wpns_Law_Violation,Pistol,Semi-Automatic,"Glock,_Inc.",NaN,45C,BLOCK,...,4500_S_6th_St,Louisville,KY,40214,-85.770469,38.188165,White,M,32.0,1.00
23659,80-17-015225,2017,2017-02-22,Wpns_Law_Violation,Pistol,Semi-Automatic,Ruger,NaN,9MM,NaN,...,NaN,Louisville,KY,40272,NaN,NaN,White,M,19.0,NaN
23660,80-17-015302,NaN,NaT,Suicide,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Louisville,KY,40210,0.000000,0.000000,NaN,NaN,NaN,0.00

In [135]:
firearm_data.to_csv('./Datasets/firearm_data_cleaned.csv')

## Summary of my Data

In [136]:
firearm_data.dtypes

incident_number                       object
year                                  object
recovery_date                 datetime64[ns]
ucr_category                          object
firearm_category                      object
firearm_subcategory                   object
firearm_manufacturer                  object
firearm_model                         object
firearm_caliber                       object
address_geocode_type                  object
block_address                         object
street_address                        object
city                                  object
state                                 object
zipcode                               object
longitude                            float64
latitude                             float64
person_recovered_from_race            object
person_recovered_from_sex             object
person_recovered_from_age            float64
confidence                           float64
dtype: object

In [137]:
summary_stats = pd.DataFrame(firearm_data.describe())
summary_stats = summary_stats.T
summary_stats.to_csv('./Datasets/summary_stats.csv')
summary_stats

,count,mean,min,25%,50%,75%,max,std
recovery_date,10552,2013-12-29 15:12:49.673995264,2008-11-29 00:00:00,2012-03-06 00:00:00,2014-03-24 00:00:00,2015-12-09 00:00:00,2017-02-22 00:00:00,NaN
longitude,8725.0,-79.440889,-122.440321,-85.789472,-85.761323,-85.694804,0.0,22.439845
latitude,8725.0,35.386305,0.0,38.168676,38.229728,38.253961,41.266511,9.994028
person_recovered_from_age,9075.0,30.497631,0.0,21.0,27.0,36.0,87.0,12.230668
confidence,8725.0,0.813987,0.0,0.664,1.0,1.0,1.0,0.290923

In [138]:
firearm_data.isna().count()

incident_number               11195
year                          11195
recovery_date                 11195
ucr_category                  11195
firearm_category              11195
firearm_subcategory           11195
firearm_manufacturer          11195
firearm_model                 11195
firearm_caliber               11195
address_geocode_type          11195
block_address                 11195
street_address                11195
city                          11195
state                         11195
zipcode                       11195
longitude                     11195
latitude                      11195
person_recovered_from_race    11195
person_recovered_from_sex     11195
person_recovered_from_age     11195
confidence                    11195
dtype: int64

In [139]:
count_data = pd.DataFrame(firearm_data.count())
count_data.columns = ['count_of_category']
count_data['dtypes'] = firearm_data.dtypes
count_data

                            count_of_category          dtypes
incident_number                         11195          object
year                                    11177          object
recovery_date                           10552  datetime64[ns]
ucr_category                            11194          object
firearm_category                         9678          object
firearm_subcategory                      9647          object
firearm_manufacturer                     9121          object
firearm_model                            5987          object
firearm_caliber                          9339          object
address_geocode_type                     8083          object
block_address                           10552          object
street_address                           8083          object
city                                    11171          object
state                                   11179          object
zipcode                                 10966          object
longitude                                8725         float64
latitude                                 8725         float64
person_recovered_from_race               9156          object
person_recovered_from_sex                9196          object
person_recovered_from_age                9075         float64
confidence                               8725         float64

In [140]:
total_data = sum(count_data['count_of_category'])
print(total_data)

201526

In [141]:
count_data['percent_null'] = (100-(firearm_data.count()/11195)*100)
count_data = count_data.reset_index()
count_data.drop(count_data[['count_of_category']], axis = 1, inplace = True)
count_data.columns = ['Category', 'Data Type', 'Missing Data %']
count_data.to_csv('./Datasets/category_values.csv', index = False)
count_data

                      Category       Data Type  Missing Data %
0              incident_number          object        0.000000
1                         year          object        0.160786
2                recovery_date  datetime64[ns]        5.743636
3                 ucr_category          object        0.008933
4             firearm_category          object       13.550692
5          firearm_subcategory          object       13.827602
6         firearm_manufacturer          object       18.526128
7                firearm_model          object       46.520768
8              firearm_caliber          object       16.578830
9         address_geocode_type          object       27.798124
10               block_address          object        5.743636
11              street_address          object       27.798124
12                        city          object        0.214381
13                       state          object        0.142921
14                     zipcode          object        2.045556
15                   longitude         float64       22.063421
16                    latitude         float64       22.063421
17  person_recovered_from_race          object       18.213488
18   person_recovered_from_sex          object       17.856186
19   person_recovered_from_age         float64       18.937025
20                  confidence         float64       22.063421

In [142]:
columns = list(firearm_data.columns)

In [143]:
firearm_data.incident_number.unique()

array(['80-06-008380', '80-06-108219', '80-08-008343', ...,
       '80-17-015000', '80-17-015225', '80-17-015302'], dtype=object)

In [144]:
category_count = firearm_data['incident_number'].count()
category_count

11195

In [145]:
def proportion_data(col_list):
    for i in col_list:
        if (firearm_data[i].dtype == 'object' or firearm_data[i].dtype == 'datetime64[ns]'):
            unique_val = list(firearm_data[""+i+""].unique())
            category_count = firearm_data[""+i+""].count()
            unique_val_df = pd.DataFrame(unique_val)
            val_counts = list()
            val_unique = list()
            for j in unique_val:
                count_unique = sum(firearm_data[""+i+""] == j)
                val_counts.append(count_unique)
                proportion_unique = (count_unique/category_count) * 100
                val_unique.append(proportion_unique)
            unique_val_df['sum'] = val_counts
            unique_val_df['proportion'] = val_unique
            unique_val_df.to_csv('./Datasets/unique_val_df_'+i+'.csv', index = False)
    return "done"

In [146]:
proportion_data(columns)

'done'

In [ ]:
matrix = firearm_data.corr(numeric_only=True)
matrix.to_csv('./Datasets/corr_matrix.csv')

In [ ]:
sns.heatmap(matrix)
plt.savefig('./CompiledImages/correlation_heatmap.png')

## Looking at the incident categories

In [ ]:
firearm_data_category = firearm_data[['ucr_category', 'incident_number']]

In [ ]:
firearm_data_category = firearm_data_category.groupby(['ucr_category']).count()
firearm_data_category.columns = ["count_of_incidents"]
firearm_data_category_csv = firearm_data_category
firearm_data_category_csv.to_csv('./Datasets/firearm_data_category.csv')

In [ ]:
firearm_data_category

In [ ]:
sq.plot(firearm_data_category['count_of_incidents'])

In [ ]:
ax1 = firearm_data_category.sort_values(by=['count_of_incidents'], ascending = False).plot(kind='bar', xlabel='', title='Firearm Confiscation Crime Types 2008-2017', figsize = (20,10))
for p in ax1.patches:
    ax1.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_recovery_crime_category.png')

### Incident Categories Log

In [ ]:
firearm_data_category_log = firearm_data_category
firearm_data_category_log['log_scale'] = np.log(firearm_data_category_log['count_of_incidents'])

In [ ]:
firearm_data_category_log

In [ ]:
null_values_dropped = firearm_data_category_log[firearm_data_category_log['log_scale'] != 0]

In [ ]:
null_values_dropped

In [ ]:
ax14 = null_values_dropped['log_scale'].sort_values(ascending = False).plot(kind='bar', xlabel='', title='Firearm Confiscation Crime Types 2008-2017', figsize = (20,10))
for p in ax14.patches:
    ax14.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_recovery_crime_category.png')

## Looking at the gun categories

In [ ]:
firearm_data_firearms = firearm_data[['firearm_category', 'firearm_subcategory']]
firearm_data_firearms['count_of_subcategory'] = firearm_data_firearms['firearm_subcategory']

In [ ]:
firearm_data_firearms_grouped = firearm_data_firearms.groupby([firearm_data_firearms['firearm_category'], firearm_data_firearms['firearm_subcategory']]).count()

In [ ]:
firearm_data_firearms_grouped

#### Log Values

In [ ]:
firearm_data_firearm_grouped_log = firearm_data_firearms_grouped
firearm_data_firearm_grouped_log['log_scale'] = np.log(firearm_data_firearm_grouped_log)

In [ ]:
firearm_data_firearm_grouped_log

In [ ]:
data_sorted_guntype = firearm_data_firearms_grouped.sort_values(by=['count_of_subcategory']).head(15)

In [ ]:
data_sorted_guntype

In [ ]:
ax8 = firearm_data_firearms_grouped.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Gun Types 2008-2017', figsize = (25,10))
for p in ax8.patches:
    ax8.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/firearm_unstacked.png')

In [ ]:
ax9 = firearm_data_firearms_grouped.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Gun Types 2008-2017', figsize = (20,15), stacked = True)
plt.savefig('./CompiledImages/firearm_stacked.png')

In [ ]:
firearm_data_firearms_subcategory = firearm_data_firearms_grouped.reset_index('firearm_category')

In [ ]:
firearm_data_firearms_subcategory = firearm_data_firearms_subcategory.sort_values(by=['count_of_subcategory'], ascending = False)

In [ ]:
firearm_data_firearms_subcategory

In [ ]:
colors = {"Pistol" : "plum", "Rifle" : "gold", "Shotgun" : "r"}

In [ ]:
ax2 = firearm_data_firearms_subcategory['count_of_subcategory'].plot(kind='bar', xlabel='', title='Types of Firearms Confiscated 2008-2017', figsize = (25,10), color = firearm_data_firearms_subcategory['firearm_category'].replace(colors))
for p in ax2.patches:
    ax2.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
pistol_label = mpatch.Patch(color = 'plum', label = "Pistol")
rifle_label = mpatch.Patch(color = 'gold', label = "Rifle")
shotgun_label = mpatch.Patch(color = 'r', label = "Shotgun")
plt.legend(handles=[pistol_label, rifle_label, shotgun_label], loc = 1)
plt.savefig('./CompiledImages/count_firearm_type.png')

#### Log Values

In [ ]:
firearm_data_firearm_grouped_log = firearm_data_firearms_grouped
# np.shape(firearm_data_firearms_grouped)
firearm_data_firearm_grouped_log['log_scale'] = np.log(firearm_data_firearm_grouped_log, where=firearm_data_firearm_grouped_log > 1)

In [ ]:
firearm_data_firearm_grouped_log

In [ ]:
value_firearm_grouped_log = firearm_data_firearm_grouped_log[firearm_data_firearm_grouped_log['log_scale'] != 0]

In [ ]:
ax15 = value_firearm_grouped_log['log_scale'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Gun Types 2008-2017 (Log)', figsize = (20,10))
for p in ax15.patches:
    ax15.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/unstacked_gun_crime_types_log')

In [ ]:
ax16 = value_firearm_grouped_log['log_scale'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Gun Types 2008-2017 (Log)', figsize = (20,10), stacked = True)
plt.savefig('./CompiledImages/stacked_gun_crime_types_log')

In [ ]:
firearm_data_subcategory_log = firearm_data_firearm_grouped_log.reset_index('firearm_category')

In [ ]:
firearm_data_subcategory_log = firearm_data_subcategory_log.sort_values(by=['count_of_subcategory'], ascending = False)
firearm_data_subcategory_log = firearm_data_subcategory_log[firearm_data_subcategory_log['log_scale'] != 0]

In [ ]:
firearm_data_subcategory_log

In [ ]:
ax17 = firearm_data_subcategory_log['log_scale'].plot(kind='bar', xlabel='', title='Types of Firearms Confiscated 2008-2017 (Log)', figsize = (25,10), color = firearm_data_subcategory_log['firearm_category'].replace(colors))
for p in ax2.patches:
    ax2.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
pistol_label = mpatch.Patch(color = 'plum', label = "Pistol")
rifle_label = mpatch.Patch(color = 'gold', label = "Rifle")
shotgun_label = mpatch.Patch(color = 'r', label = "Shotgun")
plt.legend(handles=[pistol_label, rifle_label, shotgun_label], loc = 1)
plt.savefig('./CompiledImages/count_firearm_type_log.png')

## Looking at the crimes in each zipcode

In [ ]:
firearm_data_zipcode = firearm_data[['zipcode', 'incident_number']]

In [ ]:
firearm_data_zipcode.columns = ['zipcode', 'count_of_incidents']

In [ ]:
firearm_data_zipcode = firearm_data_zipcode.groupby(['zipcode']).count()

In [ ]:
firearm_data_zipcode

In [ ]:
ax3 = firearm_data_zipcode.sort_values(by=['count_of_incidents'], ascending = False).plot(kind='bar', xlabel='', title='Zipcode Crime Counts 2008-2017', figsize = (20,10), color = 'mediumseagreen')
for p in ax3.patches:
    ax3.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_zipcode.png')

### Zipcode Log

In [ ]:
firearm_data_zipcode_log = firearm_data_zipcode
firearm_data_zipcode_log['log_values'] = np.log(firearm_data_zipcode['count_of_incidents'])
firearm_data_zipcode_log = firearm_data_zipcode_log[firearm_data_zipcode_log['log_values']!= 0]

In [ ]:
ax18 = firearm_data_zipcode_log['log_values'].sort_values(ascending = False).plot(kind='bar', xlabel='', title='Zipcode Crime Counts 2008-2017 (Log)', figsize = (20,10), color = 'mediumseagreen')
for p in ax18.patches:
    ax18.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_zipcode_log.png')

## Counts of Crime per Race

In [ ]:
firearm_data_race = firearm_data[['person_recovered_from_race', 'incident_number']]
firearm_data_race.columns = ['person_recovered_from_race', 'number_of_incidents']

In [ ]:
firearm_data_race = firearm_data_race.groupby(['person_recovered_from_race']).count()

In [ ]:
firearm_data_race

In [ ]:
ax4 = firearm_data_race.sort_values(by=['number_of_incidents'], ascending = False).plot(kind='bar', xlabel='', title='Race Crime Counts 2008-2017', figsize = (10,6), color = 'orange')
for p in ax4.patches:
    ax4.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_race.png')

### Race Log

In [ ]:
firearm_data_race_log = firearm_data_race
firearm_data_race_log['log_values'] = np.log(firearm_data_race['number_of_incidents'])
firearm_data_race_log = firearm_data_race_log[firearm_data_race_log['log_values']!= 0]

In [ ]:
ax19 = firearm_data_race_log['log_values'].sort_values(ascending = False).plot(kind='bar', xlabel='', title='Race Crime Counts 2008-2017 (Log)', figsize = (10,6), color = 'orange')
for p in ax19.patches:
    ax19.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_race_log.png')

## Counts of Crime per Sex

In [ ]:
firearm_data_sex = firearm_data[['person_recovered_from_sex', 'incident_number']]

In [ ]:
firearm_data_sex = firearm_data_sex.groupby(['person_recovered_from_sex']).count()

In [ ]:
firearm_data_sex

In [ ]:
ax5 = firearm_data_sex.sort_values(by=['incident_number'], ascending = False).plot(kind='bar', xlabel='', title='Sex Crime Counts 2008-2017', figsize = (10,6), color = 'pink')
for p in ax5.patches:
    ax5.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_sex.png')

In [ ]:
firearm_data

## Counts of Crimes per Age

In [ ]:
firearm_data_age = firearm_data[['person_recovered_from_age', 'incident_number']]

In [ ]:
firearm_data_age = firearm_data_age.groupby(['person_recovered_from_age']).count()

In [ ]:
firearm_data_age

In [ ]:
ax6 = firearm_data_age.plot(kind='bar', xlabel='', title='Age Crime Counts 2008-2017', figsize = (20,10), color = 'thistle')
for p in ax6.patches:
    ax6.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
legend = plt.legend()
legend.get_texts()[0].set_text('count_of_incidents')
plt.savefig('./CompiledImages/firearm_crime_age.png')

In [ ]:
sns.displot(firearm_data_age.index, color='thistle', bins=20)

In [ ]:
sns.displot(firearm_data_age.index, color='cadetblue', kde = True, bins = 20)
plt.savefig('./CompiledImages/age_density.png')

### Grouping Zipcode and Sex

In [ ]:
firearm_data_zip_sex = firearm_data[['zipcode', 'person_recovered_from_sex']]
firearm_data_zip_sex['count_of_crimes'] = firearm_data_zip_sex['person_recovered_from_sex']

In [ ]:
firearm_data_zip_sex = firearm_data_zip_sex.groupby([firearm_data_zip_sex['zipcode'], firearm_data_zip_sex['person_recovered_from_sex']]).count()

In [ ]:
firearm_data_zip_sex

In [ ]:
ax7 = firearm_data_zip_sex.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Zipcode/Sex 2008-2017', figsize = (25,10))
for p in ax7.patches:
    ax7.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_zip_sex_crime.png')

### Zipcode and Sex Log

In [ ]:
firearm_data_zip_sex_log = firearm_data_zip_sex
firearm_data_zip_sex_log['log_values'] = np.log(firearm_data_zip_sex_log['count_of_crimes'])
firearm_data_zip_sex_log = firearm_data_zip_sex_log[firearm_data_zip_sex_log['log_values'] != 0]

In [ ]:
ax20 = firearm_data_zip_sex_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Zipcode/Sex 2008-2017 (Log)', figsize = (25,10))
for p in ax20.patches:
    ax20.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_zip_sex_crime_log.png')

### Grouping Zipcode and Race

In [ ]:
firearm_data_zip_race = firearm_data[['zipcode', 'person_recovered_from_race']]
firearm_data_zip_race['count_of_crimes'] = firearm_data_zip_race['person_recovered_from_race']

In [ ]:
firearm_data_zip_race = firearm_data_zip_race.groupby([firearm_data_zip_race['zipcode'], firearm_data_zip_race['person_recovered_from_race']]).count()

In [ ]:
firearm_data_zip_race

In [ ]:
ax10 = firearm_data_zip_race.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Zipcode/Race 2008-2017', figsize = (30,50))
for p in ax10.patches:
    ax10.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_zip_race_crime.png')

### Zipcode and Race Log

In [ ]:
firearm_data_zip_race_log = firearm_data_zip_race
firearm_data_zip_race_log['log_values'] = np.log(firearm_data_zip_race_log['count_of_crimes'])
firearm_data_zip_race_log_zero = firearm_data_zip_race_log[firearm_data_zip_race_log['log_values'] != 0]

In [ ]:
firearm_data_zip_race_log_zero.index

In [ ]:
ax21 = firearm_data_zip_race_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Zipcode/Race 2008-2017 (Log)', figsize = (40,10))
for p in ax21.patches:
    ax21.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_zip_race_crime_log.png')

In [ ]:
norm = mpcolors.Normalize(vmin=min(firearm_data_zip_race_log_zero.log_values), vmax=max(firearm_data_zip_race_log_zero.log_values))
colors = [cmpl.Blues(norm(value)) for value in firearm_data_zip_race_log_zero.log_values]
fig = plt.gcf()
ax = fig.add_subplot()
fig.set_size_inches(20, 15)
sq.plot(label = firearm_data_zip_race_log_zero.index, sizes = firearm_data_zip_race_log_zero.log_values, color = colors)
plt.savefig('./CompiledImages/count_zip_race_crime_heatmap.png')

## Grouping zipcode and year

In [ ]:
firearm_data_zip_year = firearm_data[['zipcode', 'year']]
firearm_data_zip_year['count_of_crimes'] = firearm_data_zip_year['year']

In [ ]:
firearm_data_zip_year = firearm_data_zip_year.groupby([firearm_data_zip_year['zipcode'], firearm_data_zip_year['year']]).count()

In [ ]:
firearm_data_zip_year

In [ ]:
firearm_data_zip_year_heat = firearm_data_zip_year.reset_index()

In [ ]:
firearm_data_zip_year_heat

In [ ]:
zip_year_pivot = firearm_data_zip_year_heat.pivot("zipcode", "year", "count_of_crimes")

In [ ]:
zip_year_pivot = zip_year_pivot.replace(np.NaN, 0)

In [ ]:
zip_year_pivot

In [ ]:
fig, ax40 = plt.subplots(figsize = (15,10))
sns.heatmap(zip_year_pivot, cmap = 'Reds', robust = True, annot = True, fmt='g')
plt.savefig('./CompiledImages/zip_year_pivot.png')

In [ ]:
ax12 = firearm_data_zip_year_heat.boxplot(column="count_of_crimes", by="zipcode", figsize=(40,20), showfliers = False, showmeans = True)
plt.savefig('./CompiledImages/zip_boxplot.png')

## Zipcode and year log

In [ ]:
firearm_data_zip_year_log = firearm_data_zip_year
firearm_data_zip_year_log['log_values'] = np.log(firearm_data_zip_year_log['count_of_crimes'])
firearm_data_zip_year_log.drop('count_of_crimes', axis = 1, inplace = True)

In [ ]:
firearm_data_zip_year_log_heat = firearm_data_zip_year.reset_index()

In [ ]:
zip_year_log_pivot = firearm_data_zip_year_log_heat.pivot("zipcode", "year", "log_values")
zip_year_log_pivot = zip_year_log_pivot.replace(np.NaN, 0)
zip_year_log_pivot

In [ ]:
fig, ax22 = plt.subplots(figsize = (15,10))
sns.heatmap(zip_year_log_pivot, cmap = 'Reds', ax=ax22)
plt.savefig('./CompiledImages/zip_year_log_pivot.png')

In [ ]:
ax12 = firearm_data_zip_year_log_heat.boxplot(column="log_values", by="zipcode", figsize=(30,15), showfliers = False, showmeans = True)
plt.savefig('./CompiledImages/zip_boxplot_log.png')

### Viewing Yearly Gun Crime Count Trends for each Zipcode

In [ ]:
zip_year_line = firearm_data_zip_year

In [ ]:
zip_year_line = firearm_data_zip_year.reset_index('year')

In [ ]:
zip_year_line

In [ ]:
zip_year_raw = firearm_data[['zipcode', 'year']]

In [ ]:
def zipcode_indiv_data(zipc):
    zip_data = zip_year_raw
    search_zipcode = str(zipc)
    query = "zipcode=="+"'"+search_zipcode+"'"
    df = zip_data.query(query)
    df[zipc] = df['year']
    df.drop(df[['zipcode']], axis=1, inplace= True)
    df = df.groupby('year').count()
    df = pd.DataFrame(df)
    return df

In [ ]:
def zipcode_indiv_data_plot(zipc, ax):
    num = zip_list.index(zipc)
    plot_df = pd.DataFrame()
    for x in range(num, num+4):
        if(x < len(zip_list)):
            new_year = zipcode_indiv_data(zip_list[x])
            plot_df = pd.concat([plot_df, new_year], axis = 1)
    plot_df = plot_df.reindex(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])
    df_plot = plot_df.plot(ax = ax)
    plot_name = "./CompiledImages/zip_line_year_"+str(zipc)+".png"
    plt.savefig(plot_name)
    return df_plot

In [ ]:
zip_list = list(firearm_data_zip_year_heat['zipcode'].unique())

In [ ]:
zip_list

In [ ]:
plt.figure(figsize = (30,25))
fig.subplots_adjust(hspace=0.5)
i = 1
for j in zip_list[::4]:
    axName = 'ax'+str(i)
    axName = plt.subplot(5,2,i)
    zipcode_indiv_data_plot(j, axName)
    if(i<10):
        i += 1
plt.savefig('./CompiledImages/zipcode_trend_uneven.png')

In [ ]:
fig, axes = plt.subplots(nrows=5, ncols=2, sharex=True, sharey=True, figsize=(20,20))
axes_list = [item for sublist in axes for item in sublist] 

for j in zip_list[::4]:
    if(len(axes_list)>0):
        axName = axes_list.pop(0)
        zipcode_indiv_data_plot(j, axName)
plt.savefig('./CompiledImages/zipcode_trend_shared.png')

## Plotting Race and UCR Category

In [ ]:
firearm_data_race_ucr = firearm_data[['person_recovered_from_race', 'ucr_category']]

In [ ]:
firearm_data_race_ucr['count_of_incidents'] = firearm_data_race_ucr['ucr_category']

In [ ]:
firearm_data_race_ucr = firearm_data_race_ucr.groupby(['ucr_category', 'person_recovered_from_race']).count()

In [ ]:
firearm_data_race_ucr

In [ ]:
ax23 = firearm_data_race_ucr.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017', figsize = (30,20))
for p in ax23.patches:
    ax23.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_race_ucr_unstacked.png')

In [ ]:
ax25 = firearm_data_race_ucr.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017', figsize = (30,20), stacked = True)
plt.savefig('./CompiledImages/count_race_ucr_stacked.png')

### Race and UCR Category Log

In [ ]:
firearm_data_race_ucr_log = firearm_data_race_ucr
firearm_data_race_ucr_log['log_values'] = np.log(firearm_data_race_ucr['count_of_incidents'])
firearm_data_race_ucr_log = firearm_data_race_ucr_log[firearm_data_race_ucr_log['log_values'] != 0]

In [ ]:
ax24 = firearm_data_race_ucr_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017 (Log)', figsize = (50,20))
for p in ax24.patches:
    ax24.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_race_ucr_log_unstacked.png')

In [ ]:
ax26 = firearm_data_race_ucr_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017 (Log)', figsize = (50,20), stacked = True)
plt.savefig('./CompiledImages/count_race_ucr_log_stacked.png')

## Plotting UCR Category and Year

In [ ]:
firearm_data_year_ucr = firearm_data[['year', 'ucr_category']]

In [ ]:
firearm_data_year_ucr['count_of_incidents'] = firearm_data_year_ucr['ucr_category']

In [ ]:
firearm_data_year_ucr = firearm_data_year_ucr.groupby(['ucr_category', 'year']).count()

In [ ]:
firearm_data_year_ucr

In [ ]:
ax27 = firearm_data_year_ucr.unstack().plot(kind='barh', xlabel='', title='Gun Crimes Year/UCR Category 2008-2017', figsize = (25,15))
for p in ax27.patches:
    ax27.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_year_ucr_unstacked.png')

In [ ]:
ax28 = firearm_data_year_ucr.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Year/UCR Category 2008-2017', figsize = (30,20), stacked = True)
plt.savefig('./CompiledImages/count_year_ucr_stacked.png')

### Year and UCR Category

In [ ]:
firearm_data_ucr_year = firearm_data[['ucr_category', 'year']]

In [ ]:
firearm_data_ucr_year['count_of_incidents'] = firearm_data_ucr_year['ucr_category']

In [ ]:
firearm_data_ucr_year = firearm_data_ucr_year.groupby(['year', 'ucr_category']).count()

In [ ]:
firearm_data_ucr_year

In [ ]:
ax29 = firearm_data_ucr_year.unstack().plot(kind='barh', xlabel='', title='Gun Crimes UCR Category/Year 2008-2017', figsize = (20,25))
for p in ax29.patches:
    ax29.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_ucr_year_unstacked.png')

In [ ]:
ax28 = firearm_data_ucr_year.unstack().plot(kind='bar', xlabel='', title='Gun Crimes UCR Category/Year 2008-2017', figsize = (30,20), stacked = True)
plt.savefig('./CompiledImages/count_ucr_year_stacked.png')

### Race and UCR Category Log

In [ ]:
firearm_data_race_ucr_log = firearm_data_race_ucr
firearm_data_race_ucr_log['log_values'] = np.log(firearm_data_race_ucr['count_of_incidents'])
firearm_data_race_ucr_log = firearm_data_race_ucr_log[firearm_data_race_ucr_log['log_values'] != 0]

In [ ]:
ax24 = firearm_data_race_ucr_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017 (Log)', figsize = (50,20))
for p in ax24.patches:
    ax24.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/count_race_ucr_log_unstacked.png')

In [ ]:
ax26 = firearm_data_race_ucr_log['log_values'].unstack().plot(kind='bar', xlabel='', title='Gun Crimes Race/UCR Category 2008-2017 (Log)', figsize = (50,20), stacked = True)
plt.savefig('./CompiledImages/count_race_ucr_log_stacked.png')

### Gun Category and UCR

In [ ]:
firearm_gun_ucr = firearm_data[['firearm_category', 'ucr_category']]
firearm_gun_ucr['count_of_ucr_incidents'] = firearm_gun_ucr['ucr_category']
#firearm_gun_ucr = firearm_gun_ucr.dropna(subset = ['firearm_category'])
firearm_gun_ucr['firearm_category'] = firearm_gun_ucr.query("firearm_category == 'Pistol' or firearm_category =='Shotgun' or firearm_category == 'Rifle'")
firearm_gun_ucr = firearm_gun_ucr.groupby(['firearm_category', 'ucr_category']).count()

In [ ]:
firearm_gun_ucr

In [ ]:
ax35 = firearm_gun_ucr.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Firearm/UCR Category 2008-2017', figsize = (50,20), stacked = True)
plt.savefig('./CompiledImages/firearm_ucr_stacked.png')

In [ ]:
ax36 = firearm_gun_ucr.unstack().plot(kind='bar', xlabel='', title='Gun Crimes Firearm/UCR Category 2008-2017', figsize = (30,15))
for p in ax36.patches:
    ax36.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/firearm_ucr_unstacked.png')

### UCR and Gun Category

In [ ]:
firearm_ucr_gun = firearm_data[['firearm_category', 'ucr_category']]
firearm_ucr_gun['firearm_category'] = firearm_ucr_gun.query("firearm_category == 'Pistol' or firearm_category =='Shotgun' or firearm_category == 'Rifle'")
firearm_ucr_gun['count_of_firearm_cat'] = firearm_ucr_gun['firearm_category']
firearm_ucr_gun = firearm_ucr_gun.groupby(['ucr_category', 'firearm_category']).count()

In [ ]:
ax38 = firearm_ucr_gun.unstack().plot(kind='barh', xlabel='', title='Gun Crimes UCR Category/Firearm 2008-2017', figsize = (50,20), stacked = True)
plt.savefig('./CompiledImages/firearm_ucr_gun.png')

In [ ]:
ax39 = firearm_ucr_gun.unstack().plot(kind='barh', xlabel='', title='Gun Crimes UCR Category/Firearm 2008-2017', figsize = (30,15))
for p in ax39.patches:

    ax39.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/firearm_ucr_gun_unstacked.png')

### Zipcode Correlation

In [ ]:
zip_corr_table_all = pd.DataFrame()

In [ ]:
zipcode_corr_table_sex = firearm_data_zip_sex
zipcode_corr_table_sex = zipcode_corr_table_sex.reset_index('person_recovered_from_sex')
zipcode_corr_table_sex.drop('log_values', axis=1, inplace = True)

In [ ]:
zipcode_corr_table_sexM = zipcode_corr_table_sex[zipcode_corr_table_sex['person_recovered_from_sex'] == 'M']
zipcode_corr_table_sexM.drop('person_recovered_from_sex', axis = 1, inplace = True)
zipcode_corr_table_sexM.columns = ['count_of_crimes_M']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_sexM, how='outer')

In [ ]:
zipcode_corr_table_sexF = zipcode_corr_table_sex[zipcode_corr_table_sex['person_recovered_from_sex'] == 'F']
zipcode_corr_table_sexF.drop('person_recovered_from_sex', axis = 1, inplace = True)
zipcode_corr_table_sexF.columns = ['count_of_crimes_F']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_sexF, how='outer')

In [ ]:
zipcode_corr_table_race = firearm_data_zip_race
zipcode_corr_table_race.drop('log_values', axis = 1, inplace = True)
zipcode_corr_table_race = zipcode_corr_table_race.reset_index('person_recovered_from_race')

In [ ]:
zipcode_corr_table_raceB = zipcode_corr_table_race[zipcode_corr_table_race['person_recovered_from_race'] == 'Black']
zipcode_corr_table_raceB.drop('person_recovered_from_race', axis = 1, inplace = True)
zipcode_corr_table_raceB.columns = ['count_of_crimes_Black']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_raceB, how='outer')

In [ ]:
zipcode_corr_table_raceH = zipcode_corr_table_race[zipcode_corr_table_race['person_recovered_from_race'] == 'Hispanic']
zipcode_corr_table_raceH.drop('person_recovered_from_race', axis = 1, inplace = True)
zipcode_corr_table_raceH.columns = ['count_of_crimes_Hispanic']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_raceH, how='outer')

In [ ]:
zipcode_corr_table_raceW = zipcode_corr_table_race[zipcode_corr_table_race['person_recovered_from_race'] == 'White']
zipcode_corr_table_raceW.drop('person_recovered_from_race', axis = 1, inplace = True)
zipcode_corr_table_raceW.columns = ['count_of_crimes_White']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_raceW, how='outer')

In [ ]:
zipcode_corr_table_raceA = zipcode_corr_table_race[zipcode_corr_table_race['person_recovered_from_race'] == 'Asian']
zipcode_corr_table_raceA.drop('person_recovered_from_race', axis = 1, inplace = True)
zipcode_corr_table_raceA.columns = ['count_of_crimes_Asian']
zip_corr_table_all = zip_corr_table_all.join(zipcode_corr_table_raceA, how='outer')

In [ ]:
firearm_data_zip_year_corr = firearm_data[['zipcode', 'year']]
firearm_data_zip_year_corr['count_of_crimes'] = firearm_data_zip_year_corr['year']
firearm_data_zip_year_corr = firearm_data_zip_year_corr.groupby([firearm_data_zip_year_corr['zipcode'], firearm_data_zip_year_corr['year']]).count()
zipcode_corr_table_year = firearm_data_zip_year_corr

In [ ]:
zipcode_corr_table_year

In [ ]:
nameListZip = list()
zipcode_corr_table_year = zipcode_corr_table_year.reset_index('year')
for x in range(2008,2017):
    name = 'zipcode_corr_table_year'+ str(x)
    nameListZip.append(name)
    name = zipcode_corr_table_year[zipcode_corr_table_year['year'] == str(x)]
    name.drop('year', axis = 1, inplace = True)
    name.columns = ['count_of_crimes_'+str(x)]
    zip_corr_table_all = zip_corr_table_all.join(name, how='outer')

In [ ]:
zipcode_corr_table_ucr = firearm_data[['zipcode', 'ucr_category']]
zipcode_corr_table_ucr['count_of_crimes'] = zipcode_corr_table_ucr['ucr_category']
zipcode_ucr_list = zipcode_corr_table_ucr['ucr_category'].unique()
zipcode_corr_table_ucr = zipcode_corr_table_ucr.groupby(['zipcode', 'ucr_category']).count()
zipcode_corr_table_ucr = zipcode_corr_table_ucr.reset_index('ucr_category')

In [ ]:
nameListUcr = list()
for x in zipcode_ucr_list:
    name = 'zipcode_corr_table_ucr_'+ str(x)
    nameListUcr.append(name)
    name = zipcode_corr_table_ucr[zipcode_corr_table_ucr['ucr_category'] == str(x)]
    name.drop('ucr_category', axis = 1, inplace = True)
    name.columns = ['count_of_crimes_'+str(x)]
    zip_corr_table_all = zip_corr_table_all.join(name, how='outer')

In [ ]:
zip_corr_table_all

In [ ]:
zip_corr_table_final = zip_corr_table_all.corr()
zip_corr_table_final

In [ ]:
fig, ax40 = plt.subplots(figsize = (20,20))
sns.color_palette("viridis", as_cmap=True)
sns.heatmap(zip_corr_table_final, cmap = 'viridis', square = True, linewidth = 0.01)
plt.savefig('./CompiledImages/zipcode_correlation.png')

### Percent Increase per Race Per Zipcode Per Year

In [ ]:
race_inc_year_zip = firearm_data[['person_recovered_from_race', 'zipcode', 'year']]

In [ ]:
b_inc_year_zip = race_inc_year_zip[race_inc_year_zip['person_recovered_from_race'] == 'Black']
b_inc_year_zip = b_inc_year_zip[b_inc_year_zip['zipcode'] == '40202']
b_inc_year_zip.drop(['person_recovered_from_race','zipcode'], axis = 1, inplace = True)
b_inc_year_zip['count_of_incidents'] = b_inc_year_zip['year']
b_inc_year_zip = b_inc_year_zip.groupby('year').count()
b_inc_year_zip

In [ ]:
w_inc_year_zip = race_inc_year_zip[race_inc_year_zip['person_recovered_from_race'] == 'White']
w_inc_year_zip = w_inc_year_zip[w_inc_year_zip['zipcode'] == '40202']
w_inc_year_zip.drop(['person_recovered_from_race','zipcode'], axis = 1, inplace = True)
w_inc_year_zip['count_of_incidents'] = w_inc_year_zip['year']
w_inc_year_zip = w_inc_year_zip.groupby('year').count()
w_inc_year_zip

In [ ]:
h_inc_year_zip = race_inc_year_zip[race_inc_year_zip['person_recovered_from_race'] == 'Hispanic']
h_inc_year_zip = h_inc_year_zip[h_inc_year_zip['zipcode'] == '40202']
h_inc_year_zip.drop(['person_recovered_from_race','zipcode'], axis = 1, inplace = True)
h_inc_year_zip['count_of_incidents'] = h_inc_year_zip['year']
h_inc_year_zip = h_inc_year_zip.groupby('year').count()
h_inc_year_zip

In [ ]:
a_inc_year_zip = race_inc_year_zip[race_inc_year_zip['person_recovered_from_race'] == 'Asian']
a_inc_year_zip = a_inc_year_zip[a_inc_year_zip['zipcode'] == '40202']
a_inc_year_zip.drop(['person_recovered_from_race','zipcode'], axis = 1, inplace = True)
a_inc_year_zip['count_of_incidents'] = a_inc_year_zip['year']
a_inc_year_zip = a_inc_year_zip.groupby('year').count()
a_inc_year_zip

In [ ]:
ax41 = b_inc_year_zip.plot(xlabel='', title='Count of Incidents for People in 40202 by Race (2010-2017)', figsize = (30,15), color = 'mediumslateblue')
w_inc_year_zip.plot(color = 'pink', ax = ax41)
h_inc_year_zip.plot(color = 'seagreen', ax = ax41)
a_inc_year_zip.plot(color = 'crimson', ax = ax41)
b_label = mpatch.Patch(color = 'mediumslateblue', label = "Black")
w_label = mpatch.Patch(color = 'pink', label = "White")
h_label = mpatch.Patch(color = 'seagreen', label = "Hispanic")
a_label = mpatch.Patch(color = 'crimson', label = "Asian")
plt.legend(handles=[b_label, w_label, h_label, a_label], loc = 1)
for p in ax41.patches:
    ax41.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/40202_race_incidents.png')

### Percent Increase per Race per Year

In [ ]:
race_inc_year = firearm_data[['person_recovered_from_race', 'year']]

In [ ]:
b_inc_year = race_inc_year[race_inc_year['person_recovered_from_race'] == 'Black']
b_inc_year.drop('person_recovered_from_race', axis = 1, inplace = True)
b_inc_year['count_of_incidents'] = b_inc_year['year']
b_inc_year = b_inc_year.groupby('year').count()
b_inc_year

In [ ]:
w_inc_year = race_inc_year[race_inc_year['person_recovered_from_race'] == 'White']
w_inc_year.drop('person_recovered_from_race', axis = 1, inplace = True)
w_inc_year['count_of_incidents'] = w_inc_year['year']
w_inc_year = w_inc_year.groupby('year').count()
w_inc_year

In [ ]:
h_inc_year = race_inc_year[race_inc_year['person_recovered_from_race'] == 'Hispanic']
h_inc_year.drop('person_recovered_from_race', axis = 1, inplace = True)
h_inc_year['count_of_incidents'] = h_inc_year['year']
h_inc_year = h_inc_year.groupby('year').count()
h_inc_year

In [ ]:
a_inc_year = race_inc_year[race_inc_year['person_recovered_from_race'] == 'Asian']
a_inc_year.drop('person_recovered_from_race', axis = 1, inplace = True)
a_inc_year['count_of_incidents'] = a_inc_year['year']
a_inc_year = a_inc_year.groupby('year').count()
a_inc_year

In [ ]:
ax42 = b_inc_year.plot(xlabel='', title='Count of Incidents by Race (2010-2017)', figsize = (30,15), color = 'mediumslateblue')
w_inc_year.plot(color = 'pink', ax = ax42)
h_inc_year.plot(color = 'seagreen', ax = ax42)
a_inc_year.plot(color = 'crimson', ax = ax42)
b_label = mpatch.Patch(color = 'mediumslateblue', label = "Black")
w_label = mpatch.Patch(color = 'pink', label = "White")
h_label = mpatch.Patch(color = 'seagreen', label = "Hispanic")
a_label = mpatch.Patch(color = 'crimson', label = "Asian")
plt.legend(handles=[b_label, w_label, h_label, a_label], loc = 1)
for p in ax42.patches:
    ax42.annotate(np.round(p.get_height(),decimals=2),
                (p.get_x()+p.get_width()/2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points')
plt.savefig('./CompiledImages/total_incidents_time.png')